### ISSUE TITLE
Hide The Filament Shield

### ISSUE THREAD

**Issue by jcgmalave** [bezhanSalleh/filament-shield#103]
How can i Hide The Filament Shield according to the user role or permission?

**Comment by rushi7997** [comment]
Same

**Comment by rushi7997** [comment]
@jcgmalave I have solved it by adding this to `AuthServiceProvider`

```php
    protected $policies = [
        // 'App\Models\Model' => 'App\Policies\ModelPolicy',
        'Spatie\Permission\Models\Role' => 'App\Policies\RolePolicy',
    ];
```

and also I changed this line in the `config/filament-shield.php`
```php
    'register_role_policy' => [
        'enabled' => true,
    ],
```

and the it worked

**Comment by bezhanSalleh** [comment]
If you read the readme properly only setting it to true from config will suffice.
