### ISSUE TITLE
Custom Navigation Group

### ISSUE THREAD

**Issue by martingrondein-nls** [bezhanSalleh/filament-shield#105]
Hi there, I can't seem to place this plugin into a custom nav group - I want to place access to this plugin, so it can sit with the rest of my nav items under 'System' nav group.

These seem to be the only 3 nav options we have:

```
    'shield_resource' => [
        'navigation_sort' => -1,
        'navigation_badge' => true,
        'navigation_group' => false,
```

Would like something like:
```
    'shield_resource' => [
        'navigation_custom_group' => 'System',
```

**Comment by lloricode** [comment]
i think you can set translation for this
![Screenshot_2022-08-24_21-01-43](https://user-images.githubusercontent.com/8251344/186425175-cf4cf2e2-016e-428b-9476-aadd71b257b7.png)

**Comment by lloricode** [comment]
run `php artisan  vendor:publish`, then select number of `filament-shield-translations`

**Comment by bezhanSalleh** [comment]
@martingrondein-nls since the nav group can be translatable, having it in the config makes it useless.
and as @lloricode said, the nav group can be set through translations...
another option would be to extend Shield's `RoleResource` and overried the nav group method.
