### ISSUE TITLE
Filament Global Search enabled when this plugin is installed

### ISSUE THREAD

**Issue by martingrondein-nls** [bezhanSalleh/filament-shield#118]
Hi there

I require the Filament Global Search to be disabled while using this plugin.  It's disabled on all my resources, but I need this added to the RoleResource.php file:

```
protected static bool $isGloballySearchable = false;
```

The only way I can override this is by duplicating the [RoleResource.php](https://github.com/bezhanSalleh/filament-shield/blob/main/src/Resources/RoleResource.php) file into my resources and adding the above line.  Any chance we can get this added to Filament Shield package as a config/flag ?

Please see this discussion on disabling the Global Search: https://github.com/filamentphp/filament/discussions/3420

**Comment by bezhanSalleh** [comment]
fixed in #119

**Comment by martingrondein-nls** [comment]
Amazing! Thank you!
