### ISSUE TITLE
On upgrading an existing app from 1.x, shield:upgrade still ran DB migrations

### ISSUE THREAD

**Issue by grahammtbr** [bezhanSalleh/filament-shield#120]
On an existing app following your readme guide, after running `php artisan shield:upgrade` DB migrations still ran, dropping the existing tables, therefore losing existing roles, etc., even through the command stated the migrations would only be run on a fresh application. (This was done on a dev site, so I easily roled everything back).

I took a quick peak at the code, and it looks like it just checks for existing migrations from the original install as the condition for adding `--fresh` to the install portion. However those migration files are long gone due to cleanups.

I can work around this, but it seems odd to run `shield:install --fresh` in an command marked upgrade, and could be an issue for others.

**Comment by bezhanSalleh** [comment]
Should be any easy fix. The install part should be removed that's all.
