### ISSUE TITLE
 Data truncated for column 'model_id' when using uuid's for users

### ISSUE THREAD

**Issue by pjotrvdh** [bezhanSalleh/filament-shield#131]
When I'm using uuid's for my users I am unable to run the migration.
I've reproduced the problem in a fresh Laravel installation.

Steps to reproduce the problem:
```sh
composer create-project laravel/laravel example-app
cd ./example-app
composer require bezhansalleh/filament-shield
```
Update the database config in `.env`
Update `database/migrations/2014_10_12_000000_create_users_table.php:17` to have the following:
```php
Schema::create('users', function (Blueprint $table) {
            $table->uuid('id')->primary();
            ...
```
Add the trait `HasUuids` and `HasRoles` to the user model
Run the migration with
```sh
php artisan migrate:fresh
```
Install FIlament Shield 
```sh
php artisan shield:install --fresh
```

The following query exception is given:
```
SQLSTATE[01000]: Warning: 1265 Data truncated for column 'model_id' at row 1 (SQL: insert into `model_has_roles` (`model_id`, `model_type`, `role_id`) values (976f5174-31ec-421b-b961-116d990543eb, App\Models\User, 1))

```

**Comment by bezhanSalleh** [comment]
Not a shield issue.
https://spatie.be/docs/laravel-permission/v5/advanced-usage/uuid
