### ISSUE TITLE
Optimization if possible.

### ISSUE THREAD

**Issue by SkeyPunyapal** [bezhanSalleh/filament-shield#132]
hello, 
I was just checking the load on the page and found the role edit page is firing too many queries. it's like more than 200 and 8 of them are unique all others are duplicated as shown in the screenshot. can we optimize it?

![image](https://user-images.githubusercontent.com/112473216/194467157-e63a5150-9ef0-4402-ae96-84b6a715e247.png)

Hint: Laravel Collections on boot we can store permissions in Laravel collections and reuse them whenever required. this will reduce almost all duplicate queries.

**Comment by bezhanSalleh** [comment]
PR your solution.

**Comment by SkeyPunyapal** [comment]
Hello,

I'm sorry, I was busy somewhere and was not able to reply to you. I just show your message so here is the solution.

firstly we have to add the static variable like this.

![image](https://user-images.githubusercontent.com/112473216/195571069-b09a0475-2200-444f-9b8a-49defa6a9252.png)

after that, while getting Resource Entities Schema we have to initialize that variable like this and after that.

![image](https://user-images.githubusercontent.com/112473216/195571349-8b87c705-a8f3-4a6b-a938-2b20f02299ed.png)

and at the end, we have to use that variable while getting permissions from a database like this.

![image](https://user-images.githubusercontent.com/112473216/195571591-a411d0c8-9aa6-43a5-b202-622461546b1f.png)

and see the solution for all the duplicate queries, they are gone.

![image](https://user-images.githubusercontent.com/112473216/195572157-f4c2448d-0548-4863-be37-3af5f5d8e58e.png)
