### ISSUE TITLE
replicate

### ISSUE THREAD

**Issue by eaziweb95** [bezhanSalleh/filament-shield#134]
I have unselected replicate action in the roles attribution on my entity for one role, but with this role i always see the Replicate link in the table.
Another remark -->The pushActions in the table seems to be deprecated, is it linked ?

**Comment by bezhanSalleh** [comment]
one, not clear on what it's you are actually asking. but if the role for a resource doesn't have the replicate permission then when you click it should show a 403 forbidden message.
if you wanna hide it if the permission is not present then you need to overried the replicate method and add the condition via actions' hidden/visible methods based on it's presence.

second, it's deprecated.

these are not actually shield related so I suggest going through the beautifully crafted filament docs

**Comment by eaziweb95** [comment]
Sorry but when i click on the Recplicate link with the resource which has no replicate permission, i haven't the 403 error message
and the replicate modal is displayed
