### ISSUE TITLE
Ability to name navigation_group

### ISSUE THREAD

**Issue by hsul4n** [bezhanSalleh/filament-shield#135]
What about adding ability to change item navigation group name.

I would suggest:
```php
    'shield_resource' => [
        // 'navigation_group' => null, // Should use default group
        // 'navigation_group' => 'User', // Should use custom group name
    ],
// ..
````

**Comment by bezhanSalleh** [comment]
the navigation_group is already changeable through translation, just publish the translations and change it into whatever you want, given that it is text related it makes more sense to do it this way.
