### ISSUE TITLE
Target class [App\Policies\RolePolicy] does not exist.

### ISSUE THREAD

**Issue by abdullafahem** [bezhanSalleh/filament-shield#137]
Hi, I have a problem after I install the filament shield package shows me this error I don't know why.

I created the user from scratch and roles and permissions like resources

Can you help me, please?

`Target class [App\Policies\RolePolicy] does not exist.`

**Comment by bezhanSalleh** [comment]
If the file exists clear your config cache if not you need to generate it via generate cmd. Consult the readme
