### ISSUE TITLE
remove namespace of reources in GUI

### ISSUE THREAD

**Issue by ashek1412** [bezhanSalleh/filament-shield#138]
Hi,
How can I remove the name of namespaces of resources in the GUI
![image](https://user-images.githubusercontent.com/18645594/198613920-3f3341a7-fdf8-4bdc-9538-0da99c5bdafc.png)

thanks in advance

**Comment by bezhanSalleh** [comment]
Keep an eye out for the next release.
And please ask these sorta question on the discord channel instead of creating issues when there ain't none.

**Comment by beingvinaygupta** [comment]
in config folder there have filament-shield.php file

```
<?php

return [

    'shield_resource' => [
        'show_model_path' => false,
    ],
```

just update **show_model_path** to **false** it will work
