### ISSUE TITLE
Filament Shield has no effect for third-party pages?

### ISSUE THREAD

**Issue by socbaysky** [bezhanSalleh/filament-shield#149]
I am using this plugin: https://filamentphp.com/plugins/log-manager

In Roles manage, I do not check Log page

![image](https://user-images.githubusercontent.com/5350936/202506207-85d8d1c2-0e3b-4811-bb9d-848aae0862c4.png)

But user with this role can access that page normal

![image](https://user-images.githubusercontent.com/5350936/202506621-b5b6ea12-b682-4eb8-a83b-7124041f012b.png)

**Comment by socbaysky** [comment]
Many plugin has same issue, if I missing something, please help me. Thanks!

**Comment by bezhanSalleh** [comment]
yes you are missing something... it's in the readme. and for feature reference ask these sorta questions in filaments discord shield channel.

**Comment by gotzsys** [comment]
use HasPageShield trait

<?php

namespace App\Filament\Pages;

use ...;
use BezhanSalleh\FilamentShield\Traits\HasPageShield;

class MyPage extends Page
{
    use HasPageShield;
    ...
}
