### ISSUE TITLE
shield:generate command does not generate policies

### ISSUE THREAD

**Issue by kuchienkz** [bezhanSalleh/filament-shield#157]
`Permissions` was generated, but no `Policies` generated when a new Resource was made using `php artisan make:filament-resource Model --generate`. Running `php artisan shield:generate` also did not help.

`shield:doctor` result:

    Filament Shield ..................................................................................................................................  
    Auth Provider ......................................................................................................... App\Models\User|CONFIGURED
    Resource Badge ........................................................................................................................... ENABLED
    Resource Group ........................................................................................................................... ENABLED
    Resource Slug ....................................................................................................................... shield/roles
    Resource Sort ................................................................................................................................. -1
    Translations ....................................................................................................................... NOT PUBLISHED
    Version .................................................................................................................................... 2.3.2
    Views .............................................................................................................................. NOT PUBLISHED

`filament-shield.php` config file:

    <?php

    return [
    'shield_resource' => [
        'should_register_navigation' => true,
        'slug' => 'shield/roles',
        'navigation_sort' => -1,
        'navigation_badge' => true,
        'navigation_group' => true,
        'is_globally_searchable' => false,
        'show_model_path' => true,
    ],

    'auth_provider_model' => [
        'fqcn' => 'App\\Models\\User',
    ],

    'super_admin' => [
        'enabled' => true,
        'name' => 'super_admin',
        'define_via_gate' => false,
        'intercept_gate' => 'before', // after
    ],

    'filament_user' => [
        'enabled' => true,
        'name' => 'filament_user',
    ],

    'permission_prefixes' => [
        'resource' => [
            'view',
            'view_any',
            'create',
            'update',
            'restore',
            'restore_any',
            'replicate',
            'reorder',
            'delete',
            'delete_any',
            'force_delete',
            'force_delete_any',
        ],

        'page' => 'page',
        'widget' => 'widget',
    ],

    'entities' => [
        'pages' => true,
        'widgets' => true,
        'resources' => true,
        'custom_permissions' => false,
    ],

    'generator' => [
        'option' => 'policies_and_permissions',
    ],

    'exclude' => [
        'enabled' => true,

        'pages' => [
            'Dashboard',
        ],

        'widgets' => [
            'AccountWidget', 'FilamentInfoWidget',
        ],

        'resources' => [],
    ],

    'register_role_policy' => [
        'enabled' => true,
    ],];

**Comment by bezhanSalleh** [comment]
Actually when you generate a resource for filament, shield doesn't do anything for creating permissions. But it does give an option to generate those permissions when your create a role or edit a role via shield resource.

The shield generate command generates policies and permission and more if you look into the command's description. Long story short,
shield:generate --resource=YourResource
