### ISSUE TITLE
Non shield permissions removed from role on edit

### ISSUE THREAD

**Issue by Kobo-one** [bezhanSalleh/filament-shield#158]
Our application is using a mix of filament-shield permissions (edit articles, ...) and "other" permissions (access filament, ...). 
These "other" permissions are not related to Resources, Pages or Widgets. That means they are also not visible on the edit role page.

But when you edit a role that has these "other" permissions it will only save the shield permissions and remove all others. 

I would expect the form to only save/edit the permissions that are visible and not external ones.

Versions
bezhansalleh/filament-shield: v2.3.2
filament/filament: v2.16.10

**Comment by bezhanSalleh** [comment]
https://laravel.com/docs/9.x/eloquent-relationships#syncing-associations

So you might wanna extend the CreateRole and EditRole of RoleResource and adjust the afterCreate and afterSave hooks as per your requirements.
