### ISSUE TITLE
Deletes the custom permission i created

### ISSUE THREAD

**Issue by nospoontoday** [bezhanSalleh/filament-shield#165]
Hello, 

when I run the shield:install command, it keeps on resetting all my policies back to default. Removing all custom permissions I created. Is there a way I can retain certain policy files when running the shield:install command?

**Comment by bezhanSalleh** [comment]
Yeah, look into the generate command

**Comment by Whizboy-Arnold** [comment]
Hello @bezhanSalleh  this is the behavior too when you get into a roles then  click a role then activate Enable all Permissions currently Enabled for this role then disable. the disabling deletes all permissions including my own custom spatie permissions that i set up prior on the project. I have this set up on an existing project so there exist permissions prior to the setup.

**Comment by Whizboy-Arnold** [comment]
a quick fix would be to have the checkbox
` Forms\Components\Toggle::make('select_all') `
in RoleResource
to be wrapped in a check against a config entry that asks if to allow to globally edit  all permissions on a role directly like this
