### ISSUE TITLE
[QUESTION] How to properly deploy changes?

### ISSUE THREAD

**Issue by maxacarvalho** [bezhanSalleh/filament-shield#166]
Sorry to create an issue for this but the "Ask a question" button gives me a 404.

I'm starting a new project, your package amazing so I'm using it.  
My confusion comes around deployments and "super_admin" roles.

### Deployments

- How would be the recommended flow for deployments?
  I've created my resources locally and by doing that I can see the roles and permissions in my local DB but, how to work to get those created in production once I deploy my changes?

### Super admins
- How can I guarantee that "super_admin" users ger access to everything, always?
  While working locally I realized that even though I'm a super_admin user, when I create a new resource I don't get access to it until I update the role's permissions. Is there a way to make that happen automatically? I tried using the `spatie/laravel-permisions` [Gate::before](https://spatie.be/docs/laravel-permission/v5/basic-usage/super-admin#content-gatebefore) strategy but still doesn't work as I'd expect, do you have any suggestions?

Thank you very much.

**Comment by bezhanSalleh** [comment]
For your first point you can use
`shield:seeder`

For second you can use the the traits that come with shield `hasFilamentShield`.

For fresh resources you can checkout the `shield:generate` command there are option for this sorta thing.

**Comment by it-dubbelglas** [comment]
Setting the option
```
'super_admin' => [
    'enabled' => true,
    'name' => 'super_admin',
    'define_via_gate' => true, <----- Set this option to true
    'intercept_gate' => 'before', // after
],
```
in the `config/filament-shield.php` file, bypasses the permissions. In my application I can access anything, without permissions added to the super_admin role.
