### ISSUE TITLE
StudlyCaseResource are treat as namespace

### ISSUE THREAD

**Issue by Eighke** [bezhanSalleh/filament-shield#179]
**Context**: We just updated the package and regenerated the permissions `php artisan shield:generate`.

**Problem**: We have some resources that are using StudlyCase (e.g. `TerminationFeeResource`), it was working fine before but now it generates the permissions with `::` (e.g. `view_termination::fee`). 

From my understanding it was added some time ago to manage namespace (`/src/FilamentShield.php:97`), but it doesn't make a difference between a real namespace (e.g. `Resources\Termination\FeeResource`) and a StudlyCase resources (e.g. `Resources\TerminationFeeResource`).

Tried

```
Str::of($resource)->afterLast('Resources\\')->before('Resource')->snake()->replace('\_', '::')
```

And it looks like it works on both case, but I'm not sure if I missed something about this feature. :)

**Comment by bernhardh** [comment]
Same issue here. It looks really ugly and unlogically (for example `RecipeCategoryGroupResource` => `view_any_recipe::category::group`) and it breaks permissions when regenerating.
