### ISSUE TITLE
Widget is display along with widget name | Cannot translate widget name

### ISSUE THREAD

**Issue by Valpuia** [bezhanSalleh/filament-shield#189]
I've generate widget using filament and include `HasWidgetShield` in the widget,

When roles create/edit, under `widget tab` the name come as `Widget ClassName` (class name is the name I give when generated) image added below

**Edited**
And I cannot change translation or english word for widget (maybe I missed something).
For resource if I put my resource trans key like `nav.log.user` for user, then in `resource tab` it is coming.. but for `page` or `widget` I cannot find the work around

![Screenshot from 2023-04-27 15-43-43](https://user-images.githubusercontent.com/28250303/234809106-8cab24b2-3c2e-4e06-9991-61252e85c57d.png)

Version:
`"bezhansalleh/filament-shield": "^2.4",`
`"filament/filament": "^2.0",`
`"laravel/framework": "^10.0",`

**Comment by bezhanSalleh** [comment]
Not shield related rather a filament dependency on how you translate the widget heading or page title
