### ISSUE TITLE
Non-static method BezhanSalleh\FilamentShield\FilamentShield::getResources() cannot be called statically

### ISSUE THREAD

**Issue by Ariziky** [bezhanSalleh/filament-shield#190]
Hi. I have just updated my composer.json file and goet this issue : 
Non-static method BezhanSalleh\FilamentShield\FilamentShield::getResources() cannot be called statically.

I need help please.

I am using version 2.4.5

**Comment by bezhanSalleh** [comment]
Seems you have published the resource so republished. Or just change the use statement to use the facade instead.
