### ISSUE TITLE
 There is a performance issue

### ISSUE THREAD

**Issue by a21ns1g4ts** [bezhanSalleh/filament-shield#199]
The problem arises when dealing with a large number of roles. The code uses the reduce function on the collection of resources obtained from FilamentShield::getResources() to transform them into an array of entities. However, the process of creating a new Forms\Components\Card instance for each entity within the reduce function can be inefficient and lead to performance degradation.

This inefficiency is primarily caused by the repeated creation of objects within the iteration. Object creation can be a relatively expensive operation in terms of memory allocation and processing time, especially when performed in a loop or a high-frequency context.

In scenarios where there are a significant number of roles, the performance impact becomes more pronounced. The excessive object creation and memory allocation can lead to increased memory usage and slower execution times.

To address this performance issue, it's recommended to refactor the code to minimize the creation of Forms\Components\Card instances within the reduce function. Instead, consider extracting the logic for creating these instances to a separate method or function outside the reduce loop. This approach reduces the number of object creations and improves overall performance.

By optimizing the code in this manner, you can mitigate the performance problems associated with handling a large number of roles and enhance the efficiency of the application.

### Start solution discovery

Use Pagination: If the number of resources is extremely large, consider implementing pagination. Instead of loading all resources at once, retrieve them in smaller chunks or pages. This approach can reduce the memory footprint and improve the response time of the application.

**Comment by bezhanSalleh** [comment]
Submit a PR. Thanks 🖖

**Comment by a21ns1g4ts** [comment]
I was trie an solution thats no change the current ui

**Comment by bezhanSalleh** [comment]
i'm sorry but i don't get what you are trying to tell me here...
if you have any question feel free to ask them in the discord channel.
I will close the issue for now and if you are will you can submit a PR later.

**Comment by a21ns1g4ts** [comment]
@bezhanSalleh thanks for your reply. I wil send to you an mensage. I'm thinking the way to improve an non functional ux
