### ISSUE TITLE
Guide should cover what navigation items are available to register for users using custom navigation.

### ISSUE THREAD

**Issue by pocketnest-erik** [bezhanSalleh/filament-shield#201]
I am using custom navigation registration in my Filament implementation via the `Filament::navigation(...` method on the facade. The installation/user guide says nothing about what items are register-able in navigation for Shield and how to manually do so in a use-case like mine. I had to dig through the composer package to figure it out, which was not impossible, but still a less than ideal scenario.

Also, some comments in the config file about what each option does would be great.

**Comment by bezhanSalleh** [comment]
Send a PR to make it clear. Thanks 🖖
