### ISSUE TITLE
Issues with Entity Visibility for Different Tenant Levels Using Filament-Shield and Stancl/Tenancy

### ISSUE THREAD

**Issue by umardy** [bezhanSalleh/filament-shield#202]
I am using filament-shield in my application which also employs the stancl/tenancy package. My application has two levels of tenants: 'coordinator' and 'tenant'. These two tenant levels have different requirements; for example, Resource A should only be visible if the tenant level is 'coordinator' and hidden if the level is 'tenant'.

To achieve this, I have used the exclude option in the filament-shield config:

```
// ...
'exclude' => [
    'enabled' => true,
    'pages' => [
        'PagesA', 'PagesB'
    ],
    'widgets' => [
        'WidgetA', 'WidgetB', 'WidgetC'
    ],
    'resources' => [
        'ResourceA', 'ResourceB', 'ResourceC'
    ],
],
```

By using dynamic exclude, I was able to successfully generate resource permissions for different tenant levels:

```
if ($level == 'tenant') {
    Utils::enableGeneralExclude();
    Artisan::call('shield:generate --all --option=permissions');
} else {
    Utils::disableGeneralExclude();
    Artisan::call('shield:generate --all --option=permissions');
}
```

The permissions are correctly generated in the database. However, I encountered an issue with the visibility of all entities on the Create/Edit Role page. If filament-shield.exclude.enable is set to true, the excluded entities are hidden for both levels of tenants. Conversely, if it's set to false, they are visible for both levels.

As a temporary workaround (which is not ideal), I added this code inside the FilamentShield.php file to dynamically change the exclude config value:

```
public function getResources(): ?array
{
    return collect(Filament::getResources())
        ->unique()
        ->filter(function ($resource) {
            // I added this
            if (tenant('level') == 'coordinator') {
                Utils::disableGeneralExclude();
            }
            if (Utils::isGeneralExcludeEnabled()) {
                return !in_array(
                    Str::of($resource)->afterLast('\\'),
                    Utils::getExcludedResouces()
                );
            }
            return true;
        })
        // ....
}
// I did the same for other entities.
```

With this workaround, the entities are correctly shown or hidden on the Create/Edit Role page based on the tenant level. However, I believe that there should be a cleaner solution to handle this use case.

Thank you.

**Comment by chris-john19** [comment]
Can you share a video tutorial on how did you manage to use this Filament-plugin? Thank you!

**Comment by bezhanSalleh** [comment]
i'm glad you found a workaround. the current implementation doesn't take into account context or tenants so aside from what did would be to publish the resource and handle the context from there.
