### ISSUE TITLE
Toggle cannot active when only one item available in permissions

### ISSUE THREAD

**Issue by valpuia** [bezhanSalleh/filament-shield#204]
![Screenshot from 2023-06-30 16-38-14](https://github.com/bezhanSalleh/filament-shield/assets/28250303/b8225249-9a58-4f0d-bef6-48796e0b5edd)
If you use getPermissionPrefixes() and return only 1 permissions, then the "Check All?" toggle cannot become active (true).. And the main toggle "Select All" also become inactive

How to Reproduce
```
use BezhanSalleh\FilamentShield\Contracts\HasShieldPermissions;

class MyResource extends Resource implements HasShieldPermissions
{
    public static function getPermissionPrefixes(): array
    {
        return [
            'view_any',
        ];
    }
}
```
re-run permission command `php artisan shield:install --fresh`
Check admin panel, toggle the resource permissions and update then check.

**Comment by bezhanSalleh** [comment]
fixed in #224
