### ISSUE TITLE
Tenancy Support 🔥

### ISSUE THREAD

**Issue by Saifallak** [bezhanSalleh/filament-shield#211]
would be awesome if Tenancy supported.

**Comment by aeq-dev** [comment]
+1

**Comment by bezhanSalleh** [comment]
this is possible. but haven't had a chance to review the tenancy logic in v3. hell these days i don't get the time to release a stable version for v3. 
worry not, it's on the road map and it will be supported eventually by me or someone might PR it 🤞

**Comment by tuarrep** [comment]
Is the Team feature support (#153) could help here?

**Comment by HomaEEE** [comment]
+1

**Comment by makzumi** [comment]
@micraux yes, my PR does that (#216). For Example:
If you have 5 panels and you've got different resources, widgets, etc. set up on each and you also have an admin panel, then you can see all pages, resources widgets, etc.. roles and permissions combined in the admin panel "Filament Shield".

**Comment by erchecho** [comment]
+1

**Comment by dcresnitzky** [comment]
+1

**Comment by amigoinf** [comment]
+1

**Comment by n-ramos** [comment]
Hey guys, for me it worked, but i have a suggestion, can we imagine give such permission by tenant ? 
For example my user john doe have 2 teams, for example Team A and Team B

John doe can do all on specific resource for the team A
but John doe can only view any specific resource  on Team B

Have you got any suggestion to do that ?

**Comment by makzumi** [comment]
> Hey guys, for me it worked, but i have a suggestion, can we imagine give such permission by tenant ? For example my user john doe have 2 teams, for example Team A and Team B
> 
> John doe can do all on specific resource for the team A but John doe can only view any specific resource on Team B
> 
> Have you got any suggestion to do that ?

How about custom persmissions? I use this for panels. Then create you own traits for restrict access

**Comment by n-ramos** [comment]
> > Hey guys, for me it worked, but i have a suggestion, can we imagine give such permission by tenant ? For example my user john doe have 2 teams, for example Team A and Team B
> > John doe can do all on specific resource for the team A but John doe can only view any specific resource on Team B
> > Have you got any suggestion to do that ?
> 
> How about custom persmissions? I use this for panels. Then create you own traits for restrict access

You mean u create custom permission like team1-view-any-resource ?

**Comment by makzumi** [comment]
Create a permission resource. This way you can control shield's default permissions too:
![image](https://github.com/bezhanSalleh/filament-shield/assets/1649159/d8839cba-108e-4a9b-874b-78963d583670)

**Comment by n-ramos** [comment]
> Create a permission resource. This way you can control shield's default permissions too: ![image](https://user-images.githubusercontent.com/1649159/268993850-d8839cba-108e-4a9b-874b-78963d583670.png)

Hum i see, for your example only "admin panel" can add any permissions for specific users and teams, for example john doe is owner of Team A, then he can add permissions to users linked in this specific teams, but not in Team B. So i can't make a resource in App Panel for edit permissions of users in team A , im right ?

**Comment by n-ramos** [comment]
It can be my use case i think im going to try add specific roles as you said
in fact i woulded like to give such specific role to access specific resources or not for specific users in my teams ^^" 
Like john add jane, but she can't add a blog post for example, but john want to add bryan and bryan can add a blog post.

Like that john can configure his ACL

But as you said it can be tricky i think

**Comment by erchecho** [comment]
> There is one thing to keep in mind in my case (think as a drawback): one user can't have different role per team. It means that if I give John the `team_leader` role, he will have all this role permissions in all the teams he belongs to.

That is exactly the thing @micraux It would be awesome being able to assign different roles in different teams to the same user.

**Comment by makzumi** [comment]
> > There is one thing to keep in mind in my case (think as a drawback): one user can't have different role per team. It means that if I give John the `team_leader` role, he will have all this role permissions in all the teams he belongs to.
> 
> That is exactly the thing @micraux It would be awesome being able to assign different roles in different teams to the same user.

custom guards maybe?

**Comment by bezhanSalleh** [comment]
i'm gonna close this for now, you guys can move the conversation to the shield discord channel as thread to help others as well. as for shield supporting tenancy i haven't found a simple and fluent api to implement, is definitely something i'm thinking about but don't have a timeline for as when it will be.

**Comment by bezhanSalleh** [comment]
just for my peace of mind you guys are merging the concept of multipanels and tenancy with teams and what you guys have described here and the solution you are trying is not sound. it isn't that complex but you are making it complex for yourselves to implement. now forget the panels and the multenancy that filament provides then drive your api logic for handling tenants, teams and members then implement the your solution using filament.

**Comment by jdion84** [comment]
Damn really wanted to use this package but I need multi tenancy support 

The solution is simple - have a tenant_id column in your roles migration and then, in the role observer, you could do Filament::getTenant() to set the id automatically. 

Or check if the model for the role has a tenant_id and use that. Seems fairly simple to implement

**Comment by Saifallak** [comment]
> Damn really wanted to use this package but I need multi tenancy support
> 
> The solution is simple - have a tenant_id column in your roles migration and then, in the role observer, you could do Filament::getTenant() to set the id automatically.
> 
> Or check if the model for the role has a tenant_id and use that. Seems fairly simple to implement

isn't Spatie already have col. called `team_id` that we can use?

**Comment by nnivxix** [comment]
If you want all resources available on super_admin role where the RoleResource only /admin, you can configure on the file configuration

![image](https://github.com/bezhanSalleh/filament-shield/assets/62538473/0bd0cb15-448b-47c6-b760-277b196bfcdf)

**Comment by khalidmaquilang** [comment]
You can check my starter app.. maybe this can help you.. I created a multi-tenant  using shield plugin.. I hope you guys can improve this

https://github.com/khalidmaquilang/tenant-shield

**Comment by makzumi** [comment]
> You can check my starter app.. maybe this can help you.. I created a multi-tenant using shield plugin.. I hope you guys can improve this
> 
> https://github.com/khalidmaquilang/tenant-shield

It is private it seems or unavailable

**Comment by khalidmaquilang** [comment]
> > You can check my starter app.. maybe this can help you.. I created a multi-tenant using shield plugin.. I hope you guys can improve this
> > https://github.com/khalidmaquilang/tenant-shield
> 
> It is private it seems or unavailable

wait.. i will make it public..

**Comment by khalidmaquilang** [comment]
> > You can check my starter app.. maybe this can help you.. I created a multi-tenant using shield plugin.. I hope you guys can improve this
> > https://github.com/khalidmaquilang/tenant-shield
> 
> It is private it seems or unavailable

You can check it now.. i changed it to public
