### ISSUE TITLE
Several issues when installing with Filament v3

### ISSUE THREAD

**Issue by malle-pietje** [bezhanSalleh/filament-shield#212]
I've installed Filament v3 (3.0.8) from scratch together with Filament Shield (3.0.0-beta2) and Filament Breezy (2.0.1) and I ran into a couple of issues.

First issue is that the docs indicate you need to register the role policy like this:
```php
'register_role_policy' => true
```

while the config file uses this structure:
```php
    'register_role_policy' => [
        'enabled' => true,
    ],
```
Which of the two is correct?

Second issue: when following the instructions I get this error:
```
Target class [App\Policies\RolePolicy] does not exist.
```

After changing the policies to this, the error goes away:
```
    protected $policies = [
        'Spatie\Permission\Models\Role' => 'App\Policies\UserPolicy',
    ];
```

Am I misunderstanding the docs or is there something else wrong?

**Comment by bezhanSalleh** [comment]
the readme is not updated for v3. just made it compatible for v3 that's all. 
also you might have add the old config. so you would need to force publish the config to make sure everything is correctly there.
