### ISSUE TITLE
bug in permssions

### ISSUE THREAD

**Issue by moazzaq** [bezhanSalleh/filament-shield#213]
I give the user any role and the role as permission but the user still has access to pages that don't have permissions

**Comment by bezhanSalleh** [comment]
make sure, you use the `HasPageShield` trait to enforce permissions for the pages.
otherwise look into the trait and build your own custom logic.
the permission for the resources are enforeced via model policy but for pages there is nothing to enforce them.
It has been explained in the readme.

**Comment by shankhadevpadam** [comment]
I have created an event_manger role but I get a wired issue I didn't give the user and admin permission for this role but when I log in with the event_manger role I see a user and admin menu.

![Screenshot](https://github.com/bezhanSalleh/filament-shield/assets/3838722/c97c1af1-2c28-4498-ab5c-31e9d793fbc1)

![Screenshot](https://github.com/bezhanSalleh/filament-shield/assets/3838722/de754369-32b0-4890-85dd-c43f96ec5ad8)

when login with the event_manger role

![Screenshot](https://github.com/bezhanSalleh/filament-shield/assets/3838722/c19759e7-9e38-4b9f-a771-07827c225b1a)
