### ISSUE TITLE
user role is inactive still user can access all role permissions

### ISSUE THREAD

**Issue by justgkp** [bezhanSalleh/filament-shield#214]
I didn't give permissions to user still the user can access all the permissions. It's was working well till last update.

**Comment by bezhanSalleh** [comment]
could you be a little bit more descriptive ` didn't give permissions to user still the user can access all the permissions`.
here you mean the role resource or all the other resources? visuals with description might help much better.

**Comment by bezhanSalleh** [comment]
no response.
