### ISSUE TITLE
Wrong Permission of roles after publishing the shield

### ISSUE THREAD

**Issue by papipsycho** [bezhanSalleh/filament-shield#218]
Hello, 

I publish shield with the command : shield:publish
and after that it display into shield for my admin role 

<img width="431" alt="Screenshot 2023-08-17 at 17 33 39" src="https://github.com/bezhanSalleh/filament-shield/assets/20132010/4892e3a7-3ebd-4c25-a037-b551f0c29566">

so i decide to select all of them and after i didn't have access any more to the "Roles" menu

so i checked into the database, it created some new permissions 

<img width="867" alt="Screenshot 2023-08-17 at 17 36 13" src="https://github.com/bezhanSalleh/filament-shield/assets/20132010/22ff0ec2-7820-45a0-ae6d-953d86fb2fc5">

which are different than the basic one 

<img width="899" alt="Screenshot 2023-08-17 at 17 35 40" src="https://github.com/bezhanSalleh/filament-shield/assets/20132010/57798219-2204-441b-bf07-774f46325696">

But inside the table "role_has_permissions" it keep Only the new one "view_shield::role" instead of "view_role" and i cannot access anymore to shield

**Comment by bezhanSalleh** [comment]
when you publish, you would also need to run the `shield:generate --all` command again in order for shield to generate the permissions and the `RolePolicy` to use these new permissions.
It's recommended to not publish the resource unless you wanna change things in the resource.

**Comment by papipsycho** [comment]
Thanks a lot
