### ISSUE TITLE
Role Resource permission change causing Visual bug in Filament 3

### ISSUE THREAD

**Issue by raugadh** [bezhanSalleh/filament-shield#219]
Clicking on any Permission Switches or Check boxes causes all permissions to disappear and Select All to be disabled,
can create new Roles if only adding Name, Editing not possible for existing roles as well.

Before Changes
![image](https://github.com/bezhanSalleh/filament-shield/assets/67876352/73f7a871-1759-475c-9f7f-8cda3cfe55fb)

After changing any field other than Name or Guard
![image](https://github.com/bezhanSalleh/filament-shield/assets/67876352/eea9b588-100f-41c6-9f5b-8c1cd3d58889)

**Comment by shankhadevpadam** [comment]
Why have I got this issue?
https://github.com/bezhanSalleh/filament-shield/issues/213#issuecomment-1684882831

**Comment by raugadh** [comment]
> Everything works for me, I can't reproduce you bug... Have you tried with a fresh install?

Hey found the issue today,

Livewire 3 is Incompatible with Satie Blade Comments, Which caused this issue
