### ISSUE TITLE
The package is altering permissions it does not manage without notice

### ISSUE THREAD

**Issue by Whizboy-Arnold** [bezhanSalleh/filament-shield#222]
Hello @simonbuehler and @bezhanSalleh,
I installed your package on an already exiting project, in our system we have other custom api permissions on our users, The package is useful for managing our web permissions on filament however, it interferes with api permissions that i manage with spatie too.
There's an issue with the package where selecting "Allow All Permissions" under a specific user removes existing custom permissions. Also when it is registering the permissions after a migration, i suppose. So i end up having to have to assign the custom permissions for the user all again while they were already set for that user.

Steps to Reproduce:
Create a custom permission  directly on spatie on a tinker say:

```
            $permission = Permission::create(['name' => 'test permissions']);
            $role->givePermissionTo($permission); ///asuming role is say Admin
``` 

Click on roles under shield on filament
Click on the role used this being Admin
Click on "select All" (this includes even without deselecting)

![image](https://github.com/bezhanSalleh/filament-shield/assets/42914878/799435c4-a362-4eaf-9156-47f99b19191a)

now run a tinker to get permissions listed, our custom permission test permissions is now gone

Expected:
Choosing "Allow All Permissions" should add new permissions without removing existing ones, and ideally not touch permissions it does not manage even including on deselect.

Actual:
The current behavior erases previously assigned custom permissions when "Allow All Permissions" is used.

Additional Info:
 
Possible Solution:
The package's permission handling might need a review to prevent unintentional removal of existing permissions.

Workaround:
Manually selecting individual permissions can avoid this problem for now.

**Comment by bezhanSalleh** [comment]
given that shield only gives you the ability to create roles for filmanet entities it's up to you on how to assign them to your uses. even so, the api permission would be listed as custom permissions so i suggest creating a role for with those permissions only as 'api_access' and then your other roles with other permissions and when assigning instead of a single role you could give the users you want the api_access role as well.
