### ISSUE TITLE
Menu issue

### ISSUE THREAD

**Issue by shankhadevpadam** [bezhanSalleh/filament-shield#223]
https://github.com/bezhanSalleh/filament-shield/issues/213#issuecomment-1684882831

**Comment by bezhanSalleh** [comment]
dude use discord channel for these sorta things. when you create a resource shield discovers them but it doesn't mean they are enforced unless you it was created before shield generate --all was run. if not you need to generate policies for those resource via generate command. look into it, it has more options.

**Comment by shankhadevpadam** [comment]
The Discord channel link is broken

https://github.com/bezhanSalleh/filament-shield/discussions/new?category=q-a
