### ISSUE TITLE
unable to generate permissions & polices for new panels (3.x)

### ISSUE THREAD

**Issue by code-reflex** [bezhanSalleh/filament-shield#228]
php artisan shield:generate --all is not generating the permissions & policies for resources if they not part of the default panel.

Steps to reproduce:
1. create a new filament panel, say App
2. Add shield plugin to this panel (as documented)
3. Create a Model with its migration 
4. Generate the modelResource (filament:make-resource)
5. now, try to generate all permissions with shield:generate command.  We see that only the default (admin) panel resources are picked  up for permissions. The resource created in step 4, inside Filament/App directory are not processed.

**Comment by bezhanSalleh** [comment]
fixed in #216
