### ISSUE TITLE
Question about display presentation

### ISSUE THREAD

**Issue by ytorbyk** [bezhanSalleh/filament-shield#237]
Is there a way to configure role permissions presentation as on the [picture](https://user-images.githubusercontent.com/10007504/148662315-35d4bd74-fc1c-4f8c-8c02-689309b414b0.png) with tabs and all resources on one tab?

**Comment by bezhanSalleh** [comment]
that is v2, using toggles and checkboxes which had a performance cost. but still you can customize the columns and columnSpan to achives something similar. 
next relase will make it easier to do so. PR #238
