### ISSUE TITLE
Error when saving Shield Settings

### ISSUE THREAD

**Issue by Ceepster14** [bezhanSalleh/filament-shield#25]
Hi,

I've installed the package in a local filament project running under Xampp / PHP 8 / Laravel 8.82.0 / Windows 11 and received the following error when both trying to save and save & generate the shield settings.

mkdir(): File exists

This is returned out of  C:\xampp8\htdocs\filament_eval\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem
.php : 603

The path that's being passed into the makeDirectory function is (on my local environment):

C:\xampp8\htdocs\filament_eval\config\filament-shield.php

**Comment by bezhanSalleh** [comment]
seems a system file permission issue. haven't used xampp since late 2016.
might be a good idea to use [Laragon](https://laragon.org/).

**Comment by Ceepster14** [comment]
I've been meaning to try Laragon, so I've installed and setup the project in Laragon, run a composer update, then run php artisan shield:upgrade. I still get the error:

mkdir(): File exists

thrown from:

C:\laragon\www\filament_eval\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:602

The path being supplied is: C:\laragon\www\filament_eval\config\filament-shield.php

I think the issue here is that the call is trying to make a directory (although why I'm not sure) with the same name as the existing filament-shield.php config file.
