### ISSUE TITLE
Permissions do not work when registering custom navigation

### ISSUE THREAD

**Issue by ArtMin96** [bezhanSalleh/filament-shield#257]
Permissions do not work with [Registering custom navigation items](https://filamentphp.com/docs/3.x/panels/navigation#registering-custom-navigation-items-1)

```php
->navigation(function (NavigationBuilder $builder): NavigationBuilder {
    return $builder->items([
        ...Pages\Dashboard::getNavigationItems(),
        ...SomeResource::getNavigationItems(),
        // ...
    ])
```

**Comment by bezhanSalleh** [comment]
for custom navigation you kinda need to handle that yourself. the nav item has these two methods that you can use

```php
 ->visible(fn (): bool => auth()->user()->can('viewAny', Payment::class))
    // or
->hidden(fn (): bool => ! auth()->user()->can('viewAny', Payment::class))

NavigationItem::make('Dashboard')
                    ->icon('heroicon-o-home')
                    ->isActiveWhen(fn (): bool => request()->routeIs('filament.admin.pages.dashboard'))
                    ->url(fn (): string => Dashboard::getUrl()),
                    ->visible(fn (): bool => auth()->user()->can('page_dashboard')),
                    
```

**Comment by ArtMin96** [comment]
And in the case of `getNavigationItems`, how should I do it?
```php
public function panel(Panel $panel): Panel
{
    return $panel
        // ...
        ->navigation(function (NavigationBuilder $builder): NavigationBuilder {
            return $builder->items([
                ...UserResource::getNavigationItems(), // Can't
            ]);
        });
}
```

**Comment by Alitindrawan24** [comment]
> And in the case of `getNavigationItems`, how should I do it?
> 
> public function panel(Panel $panel): Panel
> {
>     return $panel
>         // ...
>         ->navigation(function (NavigationBuilder $builder): NavigationBuilder {
>             return $builder->items([
>                 ...UserResource::getNavigationItems(), // Can't
>             ]);
>         });
> }

Are you still experiencing this issue? I also experienced it before and this is what I did to solve it. Hope it helps

```
->navigation(function (NavigationBuilder $builder): NavigationBuilder {
   return $builder->items([
       ...[UserResource::getNavigationItems()[0]->visible(false)]
    )];
});
```
