### ISSUE TITLE
Generated permission not valid

### ISSUE THREAD

**Issue by ludndev** [bezhanSalleh/filament-shield#258]
I'm getting this unusual format for generated permisssions. 
My model name is UIFflash and permission are not using snake case.

![image](https://github.com/bezhanSalleh/filament-shield/assets/54596310/26d81219-9b2a-488d-b702-a0ae5e9548b3)

**Comment by ArtMin96** [comment]
Check this [Configure Permission Identifier](https://github.com/bezhanSalleh/filament-shield#configure-permission-identifier)

**Comment by ludndev** [comment]
@ArtMin96 It's good now. Thanks.
