### ISSUE TITLE
Duplicate role resource when using multiple panels

### ISSUE THREAD

**Issue by monzer15** [bezhanSalleh/filament-shield#263]
I think the issue originates from FilamentShieldPlugin::register method:

    public function register(Panel $panel): void
    {
        if (! Utils::isResourcePublished()) {
            $panel->resources([
                Resources\RoleResource::class,
            ]);
        }
    }

    public static function isResourcePublished(): bool
    {
        $roleResourcePath = app_path((string) Str::of('Filament\\Resources\\Shield\\RoleResource.php')->replace('\\', '/'));

        $filesystem = new Filesystem();

        return (bool) $filesystem->exists($roleResourcePath);
    }

**let's say we have 2 panels**

1- admin
path: Filament\\Admin\\Resources

2- tenant
path: Filament\\Tenant\\Resources

**The problem**

I have published the role resource for the two panels in the above paths.

the method isResourcePublished is checking in: Filament\\Resources

it should also look for RoleResource in $panel->getResourceDirectories();

**Comment by bezhanSalleh** [comment]
atm we don't have multi-panel support for shield. we'll tackle this when we implement the support for it.
