### ISSUE TITLE
Resource Protection

### ISSUE THREAD

**Issue by devhereco** [bezhanSalleh/filament-shield#266]
as per the documentation we have two traits, HasWidgetShield and HasPageShield; which works as intended. but there is one issue with the reosources files, the permission does not effect on them and they are always showen, i have tried to add HasPageShield to each page within the resource, but it did not work. and idea in how to include the resources so permissions take effect ?

**Comment by bezhanSalleh** [comment]
Please ask this sorta question in plugin's channel on filament discord.
Chances of getting an answer there is faster than opening an issue which isn't really an issue.

Thanks.
