### ISSUE TITLE
BadMethodCallException PHP 8.2.4 10.30.1 Method App\Filament\Widgets\BlogPostsChart::getHeading does not exist.

### ISSUE THREAD

**Issue by SteveLexi1491** [bezhanSalleh/filament-shield#273]
Does anyone facing this issue and know how to resolve it?
The error popup when i click on edit role for super admin.
I implemented the getHeading function but still I'm getting the error.

![image](https://github.com/bezhanSalleh/filament-shield/assets/150118348/40c4e849-92e7-4bea-a687-8aad1ffc8024)

**Comment by bezhanSalleh** [comment]
The method isn't protected it should be public. Look into the docs on how setting a heading for chart widgets work.
