### ISSUE TITLE
Hide Resource List from role

### ISSUE THREAD

**Issue by Fossil01** [bezhanSalleh/filament-shield#275]
I have a Moderator role which I want to give access to edit every Post but I don't want them to have a list in the panel with every post if that makes sense.

Giving access to 'View Post' doesn't work since it needs the post ID probably. Giving access to View any Post works but then they also get access to the table in Filament and they get a sidebar link to that page.

Any way to make this work?

**Comment by bezhanSalleh** [comment]
not an issue for inquiries like this use https://discord.com/channels/883083792112300104/927502073543675976

**Comment by bezhanSalleh** [comment]
> Yes but not everyone uses Discord :-(

Fair enough. But you use shield and filament the filament discord server is the best place to get answers faster.

Anyhow, your question is related to filament not shield. 

But if you don't list the navigation how would your moderator have access to posts? Like where he would go to list the posts?

**Comment by bezhanSalleh** [comment]
Anyhow, get on discord if you want to chat more cause right now it's unclear what you are trying to achieve. Cheers 🍻
