### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by carpad88** [bezhanSalleh/filament-shield#282]
I'm trying to install the package following the docs but I'm getting this error each time I run `php artisan shield:install`. 
- Laravel -> `v10.34.2`
- Filament ->` v3.1.7`
- Filament-shield -> `v3.1`

```
 INFO  Generating permissions ...  


   Error 

  Call to a member function getResources() on null

  at vendor/filament/filament/src/FilamentManager.php:313
    309▕      * @return array<class-string>
    310▕      */
    311▕     public function getResources(): array
    312▕     {
  ➜ 313▕         return $this->getCurrentPanel()->getResources();
    314▕     }
    315▕ 
    316▕     public function getSidebarWidth(): string
    317▕     {

      +29 vendor frames 

  30  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

```

**Comment by ziming** [comment]
Faced the same problem. The fix is for the panel you want to use shield, you need to do $panel->default()

without the call to ->default() this error will happen.

I only use shield on 1 of my 3 panels so it is fine, if you use shield on more than 1 panel, I do not know how to resolve.
