### ISSUE TITLE
custom button permissions not working  HeaderActions

### ISSUE THREAD

**Issue by benbelgacemhichem** [bezhanSalleh/filament-shield#285]
Header button permission not working for me 
i add 

ListAgents:
protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make()->label('Create Agent'),
            Actions\Action::make('publish'), / <-this new 
        ];
    }

AgentPolicy: 
/**
     * Determine whether the user can publish.
     *
     * @param  \App\Models\User  $user
     * @return bool
     */
    public function publish(User $user): bool
    {
        dd(1);
        return $user->can('publish_agent');
    }

AgentResource:
 public static function getPermissionPrefixes(): array
    {
        return [
            'view',
            'view_any',
            'create',
            'update',
            'restore',
            'restore_any',
            'replicate',
            'reorder',
            'delete',
            'delete_any',
            'force_delete',
            'force_delete_any',
            'publish'
        ];
    }
Not working

**Comment by bezhanSalleh** [comment]
as i said in the discord channel, only default resource actions uses policies, for custom actions, user the generated permission with actions's `visible()` or `hidden()` methods.
```php
Actions\Action::make('publish')
 ->visible(fn(): bool => auth()->user()->can('publish')), // ->hidden(fn(): bool => !auth()->user()->can('publish'))
 ```
