### ISSUE TITLE
Users (Assigning Roles to Users) issue

### ISSUE THREAD

**Issue by benbelgacemhichem** [bezhanSalleh/filament-shield#287]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'roles' in 'field list'

Select::make('roles')
                    ->relationship('roles', 'name')
                    ->preload()
                    ->searchable(),

**Comment by kombiahrk** [comment]
can you share the code of resource and model to provide solution

**Comment by GamendeBrian** [comment]
I assume you got this error when trying to save the user?

The select must have the property `->multiple()` else it won't work.

Or you have to change the field to a CheckboxList.

So for example:
**Select**
`Select::make('roles')->label('Roles')->multiple()->relationship('roles', 'name')->preload()->searchable(),`

**OR**

**CheckboxList**
`CheckboxList::make('roles')->label('Roles')->relationship('roles', 'name')->searchable(),`

**THIS DOESN'T WORK**
`Select::make('roles')->label('Roles')->required()->relationship('roles', 'name'),`

**Comment by bezhanSalleh** [comment]
as @GamendeBrian said!
