### ISSUE TITLE
HasPanelShield not seems to trigger created event on user

### ISSUE THREAD

**Issue by cyberdrunk2069** [bezhanSalleh/filament-shield#288]
I have a clean User model implementing HasPanelShield, upon the creation it doesn't seem to assign
the user_panel role. am i missing something? I've modified just the role name

```
'panel_user' => [
        'name' => 'staff',
        'enabled' => true,
    ],
```
And added the trait to the user model

```
class User extends Authenticatable implements FilamentUser
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;
    use HasPanelShield;
    use HasEvents;
```
Also thought the hasEvents trait has neede, but it not seems to work properly.

**Comment by bezhanSalleh** [comment]
you must have cached your configs or something because i cannot replicate your issue.
as for the `HasEvents` trait i have no idea what that is or suppose to do here.
