### ISSUE TITLE
Integrity constraint violation: 1048 Column 'team_id' cannot be null (Connection: mysql, SQL: insert into `model_has_roles` (`model_id`, `model_type`, `role_id`, `team_id`) values (4, App\Models\User, 1, ?))

### ISSUE THREAD

**Issue by yughoz** [bezhanSalleh/filament-shield#289]
<img width="1005" alt="image" src="https://github.com/bezhanSalleh/filament-shield/assets/14834359/d52152fe-fad4-4bfc-8cc6-d3b4a36823b6">

i run with team = true 
i got error 
Integrity constraint violation: 1048 Column 'team_id' cannot be null (Connection: mysql, SQL: insert into `model_has_roles` (`model_id`, `model_type`, `role_id`, `team_id`) values (4, App\Models\User, 1, ?))

**Comment by juleindev** [comment]
![Screenshot 2023-12-18 171358](https://github.com/bezhanSalleh/filament-shield/assets/22550738/68e5ebd9-0ed5-4b06-a9cf-578ce45368b5)

Same issue within filament with Multi-Tenancy, to add a role to an user Spatie use addRole method, with the Forms an attach is performed so team_id or company_id is not add in the query to the pivot table model_has_roles.

Forms\Components\Select::make('roles')
                    ->translateLabel(__('filament-shield::filament-shield.column.roles'))
                    ->relationship(name: 'roles', titleAttribute: 'name')
                    ->multiple()
                    ->preload()
                    ->searchable(),

Don't find how to add the team_id

**Comment by bezhanSalleh** [comment]
You have missed a step. Check out the base package on how to enable teams.

https://spatie.be/docs/laravel-permission/v6/basic-usage/teams-permissions

Fyi, shield doesn't have any outta box support for teams so you have to handle it yourself.

**Comment by juleindev** [comment]
I know that Shield doesn't have any outta box support for teams but it's almost work pretty well with teams just few things to do with the spatie Doc support.
The package is really well done and you made it totally extendable.

Could be a option to add a Tenant management to your documentation

Forms\Components\Select::make('roles')
                    ->translateLabel(__('filament-shield::filament-shield.column.roles'))
                    ->relationship(name: 'roles', titleAttribute: 'name')
                    ->saveRelationshipsUsing(function (Model $record, $state) {
                        $record->roles()->syncWithPivotValues($state, [config('permission.column_names.team_foreign_key') => getPermissionsTeamId()]);
                    })
                    ->multiple()
                    ->preload()
                    ->searchable(),

**Comment by batuhanhazarguler** [comment]
MakeShieldSuperAdminCommand.php 
```
        if (config('permission.teams')) {
            setPermissionsTeamId('1');
        }

        $this->superAdmin->assignRole(Utils::getSuperAdminName());

        $loginUrl = Filament::getCurrentPanel()?->getLoginUrl();

        $this->components->info("Success! {$this->superAdmin->email} may now log in at {$loginUrl}.");

        return self::SUCCESS;
```

> <img alt="image" width="1005" src="https://private-user-images.githubusercontent.com/14834359/291177287-d52152fe-fad4-4bfc-8cc6-d3b4a36823b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MjU2NDAsIm5iZiI6MTcxMjkyNTM0MCwicGF0aCI6Ii8xNDgzNDM1OS8yOTExNzcyODctZDUyMTUyZmUtZmFkNC00YmZjLThjYzYtZDNiNGEzNjgyM2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDEyMzU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmYjM4NDA1NmFlOTIzYWExN2E4OWNlZGE2YjczMjg0YTVhOTczYzVlNmFhZjA1MmI3NzhjNzg0NDViMDI2M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5i1BZLuZ5HWIm0uJLFLEpFNVTxbuoxpwEZbilOhaOxg">
> i run with team = true i got error Integrity constraint violation: 1048 Column 'team_id' cannot be null (Connection: mysql, SQL: insert into `model_has_roles` (`model_id`, `model_type`, `role_id`, `team_id`) values (4, App\Models\User, 1, ?))

**Comment by giacomomasseron** [comment]
I have the exact same error during installation, when I execute this command:

    php artisan shield:install

Since I get the error during installation, I do not know howto handle it.
