### ISSUE TITLE
In roles page (for each role) takes too much time to modify permissions 

### ISSUE THREAD

**Issue by ehs4nm** [bezhanSalleh/filament-shield#29]
Hi thanks for the good package you provide to community.
When i have many models like more than 10, In roles page (for each role) takes too much time to modify permissions. As i see in network request, the response for each modification takes a lot of resources and heavy in size (+600kb).
I'm not sure how to make it faster.

**Comment by bezhanSalleh** [comment]
I'm aware of this performance bottle-neck. its basically the same as https://discord.com/channels/883083792112300104/883085267383226478/934853347704438784 and then https://twitter.com/danjharrin/status/1485706272733380613.
i haven't had the time to move it (if possible) from livewire to alpine like what dan did with table selection but for now it's will remain the same unless someone could PR it.
