### ISSUE TITLE
Class "App\Filament\Resources\Entidade" does not exist

### ISSUE THREAD

**Issue by MarcosGit** [bezhanSalleh/filament-shield#294]
Hi every one, i have one problem with filamnet-shield, this package not find my resource show me a error at vendor/bezhansalleh/filament-shield/src/Commands/Concerns/CanGeneratePolicy.php:23 when generating permissions.

Filament: v2
Shield: v2

Can someone help me bypass this issue.

**Comment by bezhanSalleh** [comment]
you are not following the filament naming convensions, this `App\Filament\Resources\Entidade` should be `App\Filament\Resources\EntidadeResource`.
