### ISSUE TITLE
Resource permission not working

### ISSUE THREAD

**Issue by DrewNeon** [bezhanSalleh/filament-shield#296]
After installing Shield as instructed, I also installed `tomatophp/filament-users`. When logged in as super-admin, the newly-installed users resource is surely operational. Then I created a test user with `panel_user` role only, and the `panel_user` role has no permission to the user resource.

<img width="1388" alt="image" src="https://github.com/bezhanSalleh/filament-shield/assets/25809783/1ec39295-1775-4d14-a537-2f487fcd4bba">

I did enable the `register_role_policy` in filament-shild config, and included `HasRoles` and `HasPanelShield` in the user model. 
It supposes to work on the user resource per the docs quoted `Out of the box Shield handles the predefined permissions for Filament resources. So if that's all that you need you are all set.` But the test user is also able to operate the user resouce.

<img width="1535" alt="image" src="https://github.com/bezhanSalleh/filament-shield/assets/25809783/9afe7d1a-5940-43cb-a163-8e0133653b13">

What did I miss?

Enviroment info

```
PHP version: 8.2.13
Laravel version: 10.38.2
Filament version: 3.1.27
Shield version: 3.1.2

**Comment by bezhanSalleh** [comment]
in order to enforce those permission, you need to generate the policies and if the policies are for a plugin that provides resourcefull model then you need to register  it in the authservice provider.

**Comment by DrewNeon** [comment]
> in order to enforce those permission, you need to generate the policies and if the policies are for a plugin that provides resourcefull model then you need to register it in the authservice provider.

Thanks! I did it. However,  it's not quite exactly as what the docs say. May it be due to version upgrade of Shield?

After running `php artisan shield:generate --resource=user`, there's `RolePolicy.php` only in `app/Policies`. Does it suppose to generate `app/Policies/UserPolicy.php`? 

So I added `'App\Models\User' => 'App\Policies\RolePolicy',` in the AuthServiceProvider accordingly. If I need to generate policies for more resourceful models, does it overwrite or append to  'app\Policies\RolePolicy'?

**Comment by bezhanSalleh** [comment]
please read the following on how policies work.
The shield doc for policies and generate command and then 
https://laravel.com/docs/10.x/authorization#creating-policies

**Comment by DrewNeon** [comment]
> tomatophp/filament-users

Thanks for you reply! Let me break down my questions.

As you mentioned Laravel native policy, `app/Policy/UserPolicy.php` is generated by running `php artisan make:policy UserPolicy`. After reading through the Shield doc, I think the equivalent command is `php artisan shield:generate --resource=User`, is it correct? Unlike Laravel native command for policy generation, there's no `app/Policy/UserPolicy.php` after running the `shield:generate` command, even it returns successful message as follow.

```
   INFO  Successfully generated Permissions & Policies for:  

+---+----------+--------+-------------+
| # | Resource | Policy | Permissions |
+---+----------+--------+-------------+

   INFO  Permission & Policies are generated according to your config or passed options.  

   INFO  Enjoy!  
```

Without knowing the name of the newly-generated Shield policy, I don't know how to correctly apply it in the AuthServiceProvider. BTW, the package `tomatophp/filament-users` doesn't have its own model, but using the default user model at `app/Model/User.php`.

**Comment by fawaziwalewa** [comment]
The equivalent command is:

`php artisan shield:generate --resource=UserResource`
