### ISSUE TITLE
Can't assign role without team, when team feature is enabled.

### ISSUE THREAD

**Issue by bdsumon4u** [bezhanSalleh/filament-shield#298]
This package uses `spatie/laravel-permission` beyond. What if I enable the team feature in `config/permission.php`?
Then if I want to assign a role to a user, there [must be a team](https://spatie.be/docs/laravel-permission/v6/basic-usage/teams-permissions) for which the role will be assigned.
Because `team_foreign_key` is mandatory.
https://github.com/spatie/laravel-permission/blob/7c1ca135434ecedfd2132edd63929f9f797947e3/database/migrations/create_permission_tables.php.stub#L64

At this point, we've created a user but there is no team. Without any team, we'll not be able to assign role to a user.
https://github.com/bezhanSalleh/filament-shield/blob/d613db4d024bad64d91572ef1d1cdfa07d703b72/src/Commands/MakeShieldSuperAdminCommand.php#L87
We can assign a role to a user without team, only when team feature of `spatie/laravel-permission` is disabled.

**Comment by bezhanSalleh** [comment]
no support for teams feature in shield atm.
