### ISSUE TITLE
 Not a bug but a question (or feature request): How to backup the permissions so after refresh it doesn't go a way

### ISSUE THREAD

**Issue by ehs4nm** [bezhanSalleh/filament-shield#30]
Each time refreshing database with migrate:refresh i need to do all permissions again. As all permissions are stored in database it would be deleted.
Maybe when i go in production mode and all the permissions are fixed then i should make a seeder, but now when developing How to backup the permissions so after refresh it doesn't go a way?

**Comment by bezhanSalleh** [comment]
all you need to do is really, just go the `Settings` page and if everything is to your liking just hit the `Save & Generate`. No need for a seeder or anything.
