### ISSUE TITLE
Using Str::headline to display the name

### ISSUE THREAD

**Issue by gldtn** [bezhanSalleh/filament-shield#302]
I published shield views and saw that on the table you use:
```
->formatStateUsing(fn ($state): string => Str::headline($state)),
```

How can I do the same to forms & view with Select/CheckboxList?

**Comment by bezhanSalleh** [comment]
If you are talking about the components used within shield's role resource, then shield already does it for ya.
if you are on discord join filament's discord server, there we have dedicated channel for shield and these sorta questions get answered very fast.
