### ISSUE TITLE
[Feature Request] Only create seeder for permissions

### ISSUE THREAD

**Issue by Jacobtims** [bezhanSalleh/filament-shield#309]
When running the `php artisan shield:seeder` command I would like to have an option to only create the seeder for the permissions. I don't want to seed the roles with their permission, but only the permissions.
An option like `--option=[permissions_via_roles_and_permissions, permissions_via_roles, permissions]` would be nice!

**Comment by bezhanSalleh** [comment]
you are will come to submit a PR to add those options. THanks
