### ISSUE TITLE
Feature request - add Shield for Clusters

### ISSUE THREAD

**Issue by ksimenic** [bezhanSalleh/filament-shield#314]
Filament just got new Clusters feature (https://filamentphp.com/community/alexandersix-filament-v3-2#clusters and https://filamentphp.com/docs/3.x/panels/clusters). This is a new hierarchy item beside Panel, Page/Resource and Widget so adding support for it seems logical.

**Comment by bezhanSalleh** [comment]
Since clusters are essentially pages with some special functionality, and it appears that everything is managed internally in terms of access control, the current shield essentially covers it all. I don't believe there is a need to make any changes to the shield package at this time.
