### ISSUE TITLE
Svg by name

### ISSUE THREAD

**Issue by smanczak** [bezhanSalleh/filament-shield#315]
When I install this plugin i have error:
Svg by name "filament-shield::filament-shield.nav.role.icon" from set "default" not found.

![Zrzut ekranu 2024-01-18 o 12 09 12](https://github.com/bezhanSalleh/filament-shield/assets/12541118/0757f5f8-4c0e-4f4d-a065-c8df191107ee)

**Comment by bezhanSalleh** [comment]
Seems you are either not using the deafult heroicons set or you have disabled the blade ui components and using the icons by their svg name. So publish the translations and adjust the icon.

**Comment by tsangaris** [comment]
So it's what @bezhanSalleh said. 

1. Publish the translations: php artisan vendor:publish --tag="filament-shield-translations"
2. Create a folder inside lang-->vendor-->filament-shield and name it after your language with the correct language code (for Greek I have to name it "el").
3. Copy the file filament-shield.php into the newly created folder.
4. You are done!

**Comment by be9n** [comment]
I looked into #320 also but nothing is working for me, I published the translations and I have lang->vendor->filament-shield->en->filament-shield.php and it's still not seeing the translations file, I promise I did everything I could but nothing is working can you please help me? @bezhanSalleh  @tsangaris
