### ISSUE TITLE
getLocalizedPageLabel, type string, array given

### ISSUE THREAD

**Issue by bamod33** [bezhanSalleh/filament-shield#316]
> Error: BezhanSalleh\FilamentShield\FilamentShield::getLocalizedPageLabel(): Argument #1 ($page) must be of type string, array given, called in /vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 355

In function:

`public static function getPageOptions(): array

    {

        return collect(FilamentShield::getPages())

            ->flatMap(fn ($pagePermission) => [

                $pagePermission => FilamentShield::getLocalizedPageLabel($pagePermission),

            ])

            ->toArray();

    }`

(Laravel 10, PHP 8.3, Filament v3.2.3)

Previously it was working well, it seems that a composer update broke something

**Comment by fuzailhassan** [comment]
Going through the same issue, any help would be appreciated.

**Comment by bezhanSalleh** [comment]
Most likely you have published the shield resource. So republish it again and adjust your code accordingly if any.

**Comment by bamod33** [comment]
> Most likely you have published the shield resource. So republish it again and adjust your code accordingly if any.

Solved, thanks
