### ISSUE TITLE
Svg by name "filament-shield::filament-shield.nav.role.icon" from set "default" not found.

### ISSUE THREAD

**Issue by core45** [bezhanSalleh/filament-shield#320]
In one of my projects when I disable the English language and leave only Polish the package gives me this error:

`Svg by name "filament-shield::filament-shield.nav.role.icon" from set "default" not found.`

Laravel 10.41.0
PHP 8.2

Weird thing is that  in other Laravel apps (same Laravel and PHP version) it does not happen...
Any ideas?

**Comment by bezhanSalleh** [comment]
look into #315

**Comment by bahramzade** [comment]
> look into #315

not closed.

this error me active. last v laravel10x filament ...

**Comment by dedku** [comment]
Check your .env file to see what your primary language is set to. After installing Filament Shield, you will find a list of available languages for the plugin in the vendor/bezhansalleh/filament-shield/resources/lang folder. If your language is not listed, you will need to add it manually by creating a folder named after the language code used in your application, and adding a filament-shield.php file containing your translations.

en language example :
`<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Table Columns
    |--------------------------------------------------------------------------
    */

    'column.name' => 'Name',
    'column.guard_name' => 'Guard Name',
    'column.roles' => 'Roles',
    'column.permissions' => 'Permissions',
    'column.updated_at' => 'Updated At',

    /*
    |--------------------------------------------------------------------------
    | Form Fields
    |--------------------------------------------------------------------------
    */

    'field.name' => 'Name',
    'field.guard_name' => 'Guard Name',
    'field.permissions' => 'Permissions',
    'field.select_all.name' => 'Select All',
    'field.select_all.message' => 'Enable all Permissions currently <span class="text-primary font-medium">Enabled</span> for this role',

    /*
    |--------------------------------------------------------------------------
    | Navigation & Resource
    |--------------------------------------------------------------------------
    */

    'nav.group' => 'Filament Shield',
    'nav.role.label' => 'Roles',
    'nav.role.icon' => 'heroicon-o-shield-check',
    'resource.label.role' => 'Role',
    'resource.label.roles' => 'Roles',

    /*
    |--------------------------------------------------------------------------
    | Section & Tabs
    |--------------------------------------------------------------------------
    */

    'section' => 'Entities',
    'resources' => 'Resources',
    'widgets' => 'Widgets',
    'pages' => 'Pages',
    'custom' => 'Custom Permissions',

    /*
    |--------------------------------------------------------------------------
    | Messages
    |--------------------------------------------------------------------------
    */

    'forbidden' => 'You do not have permission to access',

    /*
    |--------------------------------------------------------------------------
    | Resource Permissions' Labels
    |--------------------------------------------------------------------------
    */

    'resource_permission_prefixes_labels' => [
        'view' => 'View',
        'view_any' => 'View Any',
        'create' => 'Create',
        'update' => 'Update',
        'delete' => 'Delete',
        'delete_any' => 'Delete Any',
        'force_delete' => 'Force Delete',
        'force_delete_any' => 'Force Delete Any',
        'restore' => 'Restore',
        'reorder' => 'Reorder',
        'restore_any' => 'Restore Any',
        'replicate' => 'Replicate',
    ],
];
`

**Comment by ihkaru** [comment]
hello, im getting this error too,, i did'nt change the language in env and its still en. But somehow, it works on local, but not in shared hosting environtment. I did not mess with icon setting, just making a resource. And somehow, after logging in, i got this error.

**Comment by ihkaru** [comment]
In my case, deleting files (not the folder) in bootstrap/cache solves the issue

**Comment by jarben7** [comment]
Hello, the file with the Polish translation has the wrong name, instead of a dash there is an underscore
