### ISSUE TITLE
FilamentShield::getResources() collects wrong ModelClass name Resources in function showModelPath()

### ISSUE THREAD

**Issue by eelco2k** [bezhanSalleh/filament-shield#323]
In the getResources() function of FilamentShield.php it assumes that of each $panel->getResource() the model resides in the App\Models namespace.. But that is not always the case if you override the $model in the Resource for example, or when there is no $model but there is only an setModel() or getModel() function

examples of a Resource might look like this:

```
protected static ?string $model = \App\Models\CustomDir\ModelClass::class;
```

```
protected static ?string $model = null; // or whole line not defined and takes null value from inherited Resource class 

// existence or not of the 
public function getModel() {
   return config('somepackage.model.name');
}

// existence or not of the 
public function getModel() {
   return config('somepackage.model.name');
}

```

So the function showModelPath() should check how a resource has configured its model. I tried it with ReflectionClass / ReflectionMethod and ReflectionProperty like this:

```
$reflectionClass = new \ReflectionClass($resourceFQCN);

try {
   $reflectionClass->getProperty('model');
   if (!$reflectionClass->getStaticPropertyValue('model')) {
      throw new \ErrorException();
   }
} catch (\Exception $e) {
   try {
      $reflectionClass->getMethod('getModel');
      $resourceFQCN = $resourceFQCN::getModel();
   } catch (\Exception $e) {
      try {
         $reflectionClass->getMethod('setModel');
         $resourceFQCN = $resourceFQCN::setModel();
      } catch (\Exception $e) {}
   }
}
```

And this gives a correct corresponding Model class name and path from a Filament Resource.

Code might not be perfect but hopefully it can be adjusted and added.

**Comment by bezhanSalleh** [comment]
actually it doesn't show the path(filename) for the model but rather the class for the model and it uses the resource's `getModel()` method so however you provided the model for the resource does not matter in this case.
for instance even though the `Role` model is defined via `spatie/laravel-permission` package and is being used inside the resource that shield provides, it shows its Fully Qualified Class Name as its intended.

<img width="952" alt="Screenshot 2024-02-14 at 1 19 58 PM" src="https://github.com/bezhanSalleh/filament-shield/assets/10007504/481f8361-3d74-4884-b8be-067d297b4348">

The intent behind the `showModelPath()` is to differentiate the situations where you have models with the same name but in different namespaces and/or different functionalities. for instance in the filament demo there are two `Category` models and this function helps differenctiate between them.

<img width="963" alt="Screenshot 2024-02-14 at 1 24 35 PM" src="https://github.com/bezhanSalleh/filament-shield/assets/10007504/a162e3d3-95d1-4147-89df-7a9d8396778b">

I hope this clears the issue as i understand it, therefore i will be closing the issue and its respective PR.
Unless there's something else that i haven't covered please feel free to comment and i will adjust the solution if necessary accordingly.

Thank you!

**Comment by eelco2k** [comment]
Sorry I mentioned class path but I meant class namespace. 

Have you tried using a resource without any $model specified and only a setModel() or getModel() function defined in the resource?

this PR makes sure shield always gets the class name with namespace of the model in all possible ways the resource is configured.

**Comment by bezhanSalleh** [comment]
as i mentioned it uses the resource's `getModel()` method, so however you set the model for the resource as long as the `getModel()` functions as current filament implementation expects it to then there is no issue.

**Comment by eelco2k** [comment]
I will have to check again in which case I got the error that this function could not get the corresponding Model of a resource. I believe it was with a specific filament plugin which I had to override. 

I will create a narrowed down case where I can show that this change “is needed” to work in that specific case.  

will come back with an explanation. 
thank you for your time and patience.
