### ISSUE TITLE
Too many duplicated queries by getNavigationBadge()

### ISSUE THREAD

**Issue by zenepay** [bezhanSalleh/filament-shield#326]
It seems that each raw of table will call to this function getNavigationBadge(), then it created hundreds of multiple duplicated database queries.
![image](https://github.com/bezhanSalleh/filament-shield/assets/1179823/f9645c4c-aea3-4365-af55-5b710594bbd5)
Anyway, I had minor amend to
```
    public static function getNavigationBadge(): ?string
    {
        if (!static::$count) {
            static::$count = Utils::isResourceNavigationBadgeEnabled()
                ? static::getModel()::count()
                : null;
        }
        return static::$count;
    } 
```
Hope this is the right way, otherwise please advise.

**Comment by bezhanSalleh** [comment]
don't know what is happening but cannot reproduce your issue. might be some debugbar config thingy
<img width="1512" alt="Screenshot 2024-01-28 at 3 00 27 PM" src="https://github.com/bezhanSalleh/filament-shield/assets/10007504/c6aa9d4f-b912-4572-87b6-955d967b90fd">
