### ISSUE TITLE
Don't sync permissions

### ISSUE THREAD

**Issue by suritcate** [bezhanSalleh/filament-shield#331]
Hello
My webpage do'nt update user view.

forge@kataklopbo001:~/kataklop.com$ php artisan permission:show
Guard: web
+-----------------------------------+---------------------+------------+-------------+
|                                   | gestionnaire | panel_user | super_admin |
+-----------------------------------+---------------------+------------+-------------+
| create_cavalor                    |  ✔                  |  ·         |  ✔          |
| create_cavaloradm                 |  ·                  |  ·         |  ✔          |
| create_ordersforstables           |  ·                  |  ·         |  ✔          |
| create_orderslist                 |  ·                  |  ·         |  ✔          |
| create_orderstocavalor            |  ·                  |  ·         |  ✔          |
| create_shield::role               |  ·                  |  ·         |  ✔          |
| create_user                       |  ·                  |  ·         |  ✔          |
| delete_any_cavalor                |  ✔                  |  ·         |  ✔          |
| delete_any_cavaloradm             |  ·                  |  ·         |  ✔          |
| delete_any_ordersforstables       |  ·                  |  ·         |  ✔          |
| delete_any_orderslist             |  ·                  |  ·         |  ✔          |
| delete_any_orderstocavalor        |  ·                  |  ·         |  ✔          |
| delete_any_shield::role           |  ·                  |  ·         |  ✔          |
| delete_any_user                   |  ·                  |  ·         |  ✔          |
| delete_cavalor                    |  ✔                  |  ·         |  ✔          |
| delete_cavaloradm                 |  ·                  |  ·         |  ✔          |
| delete_ordersforstables           |  ·                  |  ·         |  ✔          |
| delete_orderslist                 |  ·                  |  ·         |  ✔          |
| delete_orderstocavalor            |  ·                  |  ·         |  ✔          |
| delete_shield::role               |  ·                  |  ·         |  ✔          |
| delete_user                       |  ·                  |  ·         |  ✔          |
| force_delete_any_cavalor          |  ✔                  |  ·         |  ✔          |
| force_delete_any_cavaloradm       |  ·                  |  ·         |  ✔          |
| force_delete_any_ordersforstables |  ·                  |  ·         |  ✔          |
| force_delete_any_orderslist       |  ·                  |  ·         |  ✔          |
| force_delete_any_orderstocavalor  |  ·                  |  ·         |  ✔          |
| force_delete_any_user             |  ·                  |  ·         |  ✔          |
| force_delete_cavalor              |  ✔                  |  ·         |  ✔          |
| force_delete_cavaloradm           |  ·                  |  ·         |  ✔          |
| force_delete_ordersforstables     |  ·                  |  ·         |  ✔          |
| force_delete_orderslist           |  ·                  |  ·         |  ✔          |
| force_delete_orderstocavalor      |  ·                  |  ·         |  ✔          |
| force_delete_user                 |  ·                  |  ·         |  ✔          |
| page_barcodereader                |  ·                  |  ·         |  ✔          |
| page_Mainpage                     |  ·                  |  ·         |  ✔          |
| page_Scanean                      |  ·                  |  ·         |  ✔          |
| page_Scaninfos                    |  ·                  |  ·         |  ✔          |
| page_Scanmain                     |  ·                  |  ·         |  ✔          |
| page_Settings                     |  ·                  |  ·         |  ✔          |
| reorder_cavalor                   |  ✔                  |  ·         |  ✔          |
| reorder_cavaloradm                |  ·                  |  ·         |  ✔          |
| reorder_ordersforstables          |  ·                  |  ·         |  ✔          |
| reorder_orderslist                |  ·                  |  ·         |  ✔          |
| reorder_orderstocavalor           |  ·                  |  ·         |  ✔          |
| reorder_user                      |  ·                  |  ·         |  ✔          |
| replicate_cavalor                 |  ✔                  |  ·         |  ✔          |
| replicate_cavaloradm              |  ·                  |  ·         |  ✔          |
| replicate_ordersforstables        |  ·                  |  ·         |  ✔          |
| replicate_orderslist              |  ·                  |  ·         |  ✔          |
| replicate_orderstocavalor         |  ·                  |  ·         |  ✔          |
| replicate_user                    |  ·                  |  ·         |  ✔          |
| restore_any_cavalor               |  ✔                  |  ·         |  ✔          |
| restore_any_cavaloradm            |  ·                  |  ·         |  ✔          |
| restore_any_ordersforstables      |  ·                  |  ·         |  ✔          |
| restore_any_orderslist            |  ·                  |  ·         |  ✔          |
| restore_any_orderstocavalor       |  ·                  |  ·         |  ✔          |
| restore_any_user                  |  ·                  |  ·         |  ✔          |
| restore_cavalor                   |  ✔                  |  ·         |  ✔          |
| restore_cavaloradm                |  ·                  |  ·         |  ✔          |
| restore_ordersforstables          |  ·                  |  ·         |  ✔          |
| restore_orderslist                |  ·                  |  ·         |  ✔          |
| restore_orderstocavalor           |  ·                  |  ·         |  ✔          |
| restore_user                      |  ·                  |  ·         |  ✔          |
| update_cavalor                    |  ✔                  |  ·         |  ✔          |
| update_cavaloradm                 |  ·                  |  ·         |  ✔          |
| update_ordersforstables           |  ·                  |  ·         |  ✔          |
| update_orderslist                 |  ·                  |  ·         |  ✔          |
| update_orderstocavalor            |  ·                  |  ·         |  ✔          |
| update_shield::role               |  ·                  |  ·         |  ✔          |
| update_user                       |  ·                  |  ·         |  ✔          |
| view_any_cavalor                  |  ✔                  |  ·         |  ✔          |
| view_any_cavaloradm               |  ·                  |  ·         |  ✔          |
| view_any_ordersforstables         |  ·                  |  ·         |  ✔          |
| view_any_orderslist               |  ·                  |  ·         |  ✔          |
| view_any_orderstocavalor          |  ·                  |  ·         |  ✔          |
| view_any_shield::role             |  ·                  |  ·         |  ✔          |
| view_any_user                     |  ·                  |  ·         |  ✔          |
| view_cavalor                      |  ✔                  |  ·         |  ✔          |
| view_cavaloradm                   |  ·                  |  ·         |  ✔          |
| view_ordersforstables             |  ·                  |  ·         |  ✔          |
| view_orderslist                   |  ·                  |  ·         |  ✔          |
| view_orderstocavalor              |  ·                  |  ·         |  ✔          |
| view_shield::role                 |  ·                  |  ·         |  ✔          |
| view_user                         |  ·                  |  ·         |  ✔          |
+-----------------------------------+---------------------+------------+-------------+

I check one user with gestionnaire but when i connect with this user, i don't see cavalor ressources ?

maybe i need to do somethings ? 
thanks

**Comment by bezhanSalleh** [comment]
Checkout filaments panel user authorization.
