### ISSUE TITLE
Teams Feature

### ISSUE THREAD

**Issue by paulmercs** [bezhanSalleh/filament-shield#342]
When I set the teams feature to true, all the permissions assigned to a role that is assigned to that team is not working I mean only the dashboard menu is showing.  What am i missing?

![Screenshot 2024-03-02 184839](https://github.com/bezhanSalleh/filament-shield/assets/136664232/1e33efc6-74e2-4a66-b4a1-6567a05972e6)

**Comment by agharium** [comment]
Man, I really so need this..

**Comment by wejrcze** [comment]
same here, team features need to be implemented 👍 , it's really cool feature and all these filament auth plugins are missing this feature working out of the box

**Comment by paulmercs** [comment]
Let's wait for the team feature 

> same here, team features need to be implemented 👍 , it's really cool feature and all these filament auth plugins are missing this feature working out of the box

Let's wait for the Team Feature

**Comment by cirino** [comment]
Let's wait 🚀

**Comment by AkikiCharbel** [comment]
You can utilize the filament tenant feature, along with the role model, by setting is_scoped_to_tenant to true in the shield configuration. However, you may need to adjust some logic depending on individual project requirements. It is certainly feasible. In my case, I modified the role resource to include a teams dropdown and adapted some aspects of my project's business logic accordingly.

**Comment by bezhanSalleh** [comment]
Unless someone PRs it with tests i'm not going to implemented anytime soon.
