### ISSUE TITLE
Add Roles And Permissions To user Resource

### ISSUE THREAD

**Issue by Dr-Maspix** [bezhanSalleh/filament-shield#345]
Dear, 
Thanks For your great plugin
Can you help me with adding some roles with permissions to user resource or admin resource ? 

Regards,

**Comment by micraux** [comment]
Hello,

What is your problem?

Basically, you just have to go to the ROLE menu and click on CREATE...

Can you provide more information on the issue you are facing?

**Comment by bezhanSalleh** [comment]
already documented https://github.com/bezhanSalleh/filament-shield?tab=readme-ov-file#users-assigning-roles-to-users
