### ISSUE TITLE
Problem when using Laravel modules nwidart package

### ISSUE THREAD

**Issue by AHMED-GAMAL-AG** [bezhanSalleh/filament-shield#351]
I am usng the Laravel modules nwidart package to make the app modular 

https://github.com/nWidart/laravel-modules 

i get ` SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'permissions' already exists `  error as the permissions table already exists in this path: `Modules\User\Database\migrations\2024_03_20_091410_create_permission_tables.php` so when running `php artisan shield:install` it creates the permissions migration again in this path `database\migrations\2024_03_20_095929_create_permission_tables.php` 

the solution is to allow defining custom path to the Permissions migration file in the `filament-shield.php` config

**Comment by bezhanSalleh** [comment]
not planned but maybe when i get some free time.
