### ISSUE TITLE
Tab bug in other languages (chinese and khmer)

### ISSUE THREAD

**Issue by valpuia604** [bezhanSalleh/filament-shield#357]
The tab is auto selected if I used non english language (I checked only `zh_CN` and `km`)
[Screencast from 03-29-2024 11:44:03 AM.webm](https://github.com/bezhanSalleh/filament-shield/assets/141896542/4bb2bf94-8530-4238-a7f2-4535e851fbff)

**Comment by curder** [comment]
Found the same problem, Thanks for your issue.
