### ISSUE TITLE
Cluster page not working

### ISSUE THREAD

**Issue by valpuia604** [bezhanSalleh/filament-shield#358]
Cluster page is not working properly when using `HasPageShield` traits

Reproduction repo: https://github.com/valpuia604/cluster-shield

Another issues:
in page tab, the cluster is also displaying. Not sure this is bug or not but it does not need to display IMO because that cluster is like a wrapper only.

![Screenshot from 2024-04-03 10-33-34](https://github.com/bezhanSalleh/filament-shield/assets/141896542/9146e490-c5ba-4da9-9488-b7051c225bb3)
Using above repo, here "Settings" is cluster and "About settings" is page inside cluster

**Comment by iRaziul** [comment]
Does resources inside cluster works?
For the the permission is not working properly, anyone can access the resources of the cluster. (Resource eg: `App\Filament\Clusters\Resources\Address\AreaResource`)
