### ISSUE TITLE
Role CRUD accessibility is bypassed

### ISSUE THREAD

**Issue by blalmal10a** [bezhanSalleh/filament-shield#364]
Role can be accessed by user with/without any role in latest release i.e. version [3.2.4](https://packagist.org/packages/bezhansalleh/filament-shield#3.2.4).

Using [3.2.3](https://packagist.org/packages/bezhansalleh/filament-shield#3.2.3) for now.

**Comment by Solankill** [comment]
Are your referring to the Roles to show up in the Nav? If so you can edit config/filament-shield.php. 

` 'shield_resource' => [
        'should_register_navigation' => false, //Change to False
        ]`

**Comment by Solankill** [comment]
This may help - 

You need to mark this as true. This fixed it for me. 
`
'register_role_policy' => [
    'enabled' => true,
],`

**Comment by blalmal10a** [comment]
> This may help -
> 
> You need to mark this as true. This fixed it for me. ` 'register_role_policy' => [ 'enabled' => true, ],`

THANK YOU
