### ISSUE TITLE
Documentation Update for Laravel 11 - Custom folder structure for Models or Third-Party Plugins

### ISSUE THREAD

**Issue by Solankill** [bezhanSalleh/filament-shield#366]
Regarding Custom folder structure for Models or Third-Party Plugins. With Laravel 11, you must now do this. 

`namespace App\Providers;

use Illuminate\Support\Facades\Gate;
use Illuminate\Support\ServiceProvider;
use RickDBCN\FilamentEmail\Models\Email;
use App\Policies\EmailPolicy;

class AuthServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->registerPolicies(); // Manually register policies

        // Manually define gates or policies if needed
        Gate::policy(Email::class, EmailPolicy::class);
 
    }

    protected function registerPolicies()
    {
        // Manually register each policy
        Gate::policy('RickDBCN\FilamentEmail\Models\Email', 'App\Policies\EmailPolicy');
    }

    public function register()
    {
        //
    }
}
`

**Comment by bezhanSalleh** [comment]
This aint an issue, you could submit a pr to update the docs
