### ISSUE TITLE
Role Resource is accessible for everyone

### ISSUE THREAD

**Issue by jals-es** [bezhanSalleh/filament-shield#367]
Hi, there are problems with the permissions of RoleResource because it's accesible for everyone without having role or if his role doesn't have role permissions.
<img width="1296" alt="Captura de pantalla 2024-04-16 a las 12 48 53" src="https://github.com/bezhanSalleh/filament-shield/assets/31510870/98cd64e1-cbb7-4e59-b074-f974166e6d07">

**Comment by jals-es** [comment]
As I can see, I have this role permisons on resources tabs:
<img width="1241" alt="Captura de pantalla 2024-04-16 a las 12 51 51" src="https://github.com/bezhanSalleh/filament-shield/assets/31510870/32e7c831-73b5-4d82-912f-09849d01e9c2">

But if I active custom permisions I can see this other shield permissions:
<img width="839" alt="Captura de pantalla 2024-04-16 a las 12 51 58" src="https://github.com/bezhanSalleh/filament-shield/assets/31510870/14b03bd5-d513-4bbd-9e96-f974a6a86cc2">


I think the permissions are duplicated.

**Comment by bezhanSalleh** [comment]
If you don't run the fresh flag when you you publish or change a resource's namespace new roles will be generated.

**Comment by PLGUPICTO** [comment]
@bezhanSalleh I have similar problem after composer update upgraded it to 3.2.4. I reverted back to 3.2.1 and it doesn't have the problem. I haven't publish or change resources.

**Comment by flightepic** [comment]
same issue here

**Comment by dominikgeimer** [comment]
I also have the same issue on a fresh Laravel app.

**Comment by bezhanSalleh** [comment]
Try #372 n let me know

**Comment by dominikgeimer** [comment]
Yes, it works. It fixed the problem for me! Thank you!
