### ISSUE TITLE
Model with two words has unexpected permission name

### ISSUE THREAD

**Issue by scottgrayson** [bezhanSalleh/filament-shield#369]
Steps to reproduce:

1. create a model with two words e.g. ZipCode
2. edit a role and give permission to view any zip code.

result:
new permission gets created called "view_any_zip::code"

expected:
the existing permission "view_any_zip_code" should be attached to the role

**Comment by bezhanSalleh** [comment]
That's the default behavior, if you want to change it read **Configure Permission Identifier** docs section.

**Comment by Raffi-001** [comment]
@bezhanSalleh I had the same issue I fixed it by Configuring Permission Identifier like you suggested. 

However, the default behavior works only if the Model name is a single word. 

Works for 
`\App\Filament\Resources\ZipResource; \\ view_any_zip`

But not for. Not technincal problem but the formatting is annoying
`\App\Filament\Resources\ZipCodeResource; \\ view_any_zip::code`

**Comment by lukasinko** [comment]
I'm putting here this solution which works for Models with more words (just in case someone would like it as well):

```
Str::of($resource)
    ->afterLast('Resources\\')
    ->before('Resource')
    ->replaceLast('\\', '::')
    ->replace('\\', '.')
    ->lower()
 ```

It will result in eg. `view_any_shop.offer::weboffer` (Filament/Resources/Shop/Offer/WebOfferResource), `view_any_shop::weboffer` (Filament/Resources/Shop/WebOfferResource). Dots are representing package structure and after `::` Resource name in lowercase.
