### ISSUE TITLE
Cannot restrict user from editing another user's entries

### ISSUE THREAD

**Issue by ap1969** [bezhanSalleh/filament-shield#37]
Hi,
Not sure if this is a problem on my end, or not, so hoping someone can help.

I've got the roles for a Timer resource set up as follows:

![image](https://user-images.githubusercontent.com/1629592/165167039-a0382a69-9e28-4edc-b155-c903f9bfd77b.png)

I think this means that the user can create/edit/delete/view their own Timers, but not someone else's.

User 3 has the following Timer currently set up:
![image](https://user-images.githubusercontent.com/1629592/165167424-db91e6a7-3ab0-47b3-be21-e4ba15950d2a.png)

However, if I log in as user 3 then go to the edit page for a Timer for user 1, I get the form to edit the Timer, and the changes are saved:
![image](https://user-images.githubusercontent.com/1629592/165167725-aeb679c4-252d-4fdd-b2ae-689248d59e0e.png)

Shouldn't the form reject User 3 when they try to edit user 1's entry?

Regards,
Andy

**Comment by quasiperfect** [comment]
i have the same question. @ap1969 did you solve this ?

**Comment by ap1969** [comment]
Not yet.

**Comment by bezhanSalleh** [comment]
@ap1969 you could do this in a couple of ways, but one way would be to adjust the `TimerPolicy`. By default shield will generate the following policy method for update:
```php
    /**
     * Determine whether the user can update the timer.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Auth\Access\Response|bool
     */
    public function update(User $user)
    {
        return $user->can('update_timer');
    }
 ```
 so for your situation to restrict users to only update their own timer you would need to update the above policy method as follow:
 ```php
    /**
     * Determine whether the user can update his/her timer.
     *
     * @param  \App\Models\User  $user
     * @param  \App\Models\Timer  $timer
     * @return \Illuminate\Auth\Access\Response|bool
     */
    public function update(User $user, Timer $timer)
    {
        return $user->can('update_author') && $user->id === $timer->user_id;
    }
```
Now shield takes care of the mundane boilerplate stuff, and how you define your logic is up to you 😇
Same goes for other methods... for more info  https://laravel.com/docs/9.x/authorization#writing-policies

~ cheers 🍺

**Comment by hardiklakhalani** [comment]
Hi, could someone help me please? I'm unable to see the `Addresses` in the navigation bar. and if I try to access the addresses route, it's giving 403 Unauthorize.

403 at `http://example.test/dashboard/addresses`

This is the policy status:
<img width="1696" alt="image" src="https://github.com/bezhanSalleh/filament-shield/assets/82162165/7a9abeb7-5e6f-4170-9d2a-fcdc706b675f">
<img width="713" alt="image" src="https://github.com/bezhanSalleh/filament-shield/assets/82162165/86511c67-70f9-469f-9350-b1285270849b">
