### ISSUE TITLE
Role Resource is accessible for everyone

### ISSUE THREAD

**Issue by chrbox** [bezhanSalleh/filament-shield#372]
After updating all users have access to the RoleResource in the panel. There are no permissions set for the role of the user.

**Comment by dominikgeimer** [comment]
Yes, it works. It fixed the problem for me! Thank you!

**Comment by hyknn** [comment]
If you're using Laravel 11, you can also fix it by adding this on your AppServiceProvider.php

```
use Spatie\Permission\Models\Role;
use App\Policies\RolePolicy;
use Illuminate\Support\Facades\Gate;

public function boot(): void
{
    Gate::policy(Role::class, RolePolicy::class);
}
```

**Comment by bezhanSalleh** [comment]
> If you're using Laravel 11, you can also fix it by adding this on your AppServiceProvider.php
> 
> 
> 
> ```
> 
> use Spatie\Permission\Models\Role;
> 
> use App\Policies\RolePolicy;
> 
> use Illuminate\Support\Facades\Gate;
> 
> 
> 
> public function boot(): void
> 
> {
> 
>     Gate::policy(Role::class, RolePolicy::class);
> 
> }
> 
> ```

You don't really need this, because its already being handled by shield. you just need to turn it on from the config.
