### ISSUE TITLE
Edit Role doesn't populate role name

### ISSUE THREAD

**Issue by dutypro** [bezhanSalleh/filament-shield#375]
When clicking "edit" on role, the edit screen doesn't display the role name in the "name" field on the form or the guard name.

![Screenshot 2024-05-03 at 19 09 37](https://github.com/bezhanSalleh/filament-shield/assets/38077637/7d784cd1-a988-4859-ba0a-c36686584c67)

![Screenshot 2024-05-03 at 19 10 17](https://github.com/bezhanSalleh/filament-shield/assets/38077637/cb59be1d-d5d2-4b73-aac7-7f9615610927)

**Comment by bezhanSalleh** [comment]
might be some miss-configuration. otherwise submit a repro repo.
