### ISSUE TITLE
cannot create or edit role

### ISSUE THREAD

**Issue by fhsdmhacc** [bezhanSalleh/filament-shield#376]
I had a previous project, but suddenly an error appeared count(): Argument #1 ($value) must be of type Countable|array, null given

![image](https://github.com/bezhanSalleh/filament-shield/assets/103301588/55f376ca-6c36-47c4-8f00-728b77e8dd9b)

**Comment by lukeholder** [comment]
Solved by removing the published filament vendor views (no need to have a copy in the app as they get outdated quickly)
