### ISSUE TITLE
Error expect string but object given when editing role

### ISSUE THREAD

**Issue by lukeholder** [bezhanSalleh/filament-shield#377]
Clicked edit role after install

Stack trace: https://flareapp.io/share/pPvAXg9m

bezhansalleh/filament-shield 3.2.4
filament/filament 3.2.73
filament/forms 3.2.73
laravel/framework 11.6.0

**Comment by bezhanSalleh** [comment]
might be a filament issue, update to the latest and if issue persists submit a repro repo.
