### ISSUE TITLE
When using github action to test, the project trait HasPanelShield try to assign role to user in step of php artisan key:generate

### ISSUE THREAD

**Issue by soap** [bezhanSalleh/filament-shield#378]
The problem is ServiceProvider was called during key:generate command, the trait try to assign role if panel_user role was enabled. But the migration was not run yet. So it failed the test.

If I diasble panel_user role before php artisan key:generate it is ok. But I have to enable it before testing using ENV variable.
![image](https://github.com/bezhanSalleh/filament-shield/assets/1073690/7611333b-673b-4a4b-9026-fe65e7c5aa67)

Any suggestion for this issue? Thanks in advance.

**Comment by bezhanSalleh** [comment]
hmm.. can you change the order of tests? other than this don't know much about testing apologies.
