### ISSUE TITLE
Generating all policies for a specific panel

### ISSUE THREAD

**Issue by benzwebdev** [bezhanSalleh/filament-shield#379]
Good day!

Is there a way to generate all policies from a specific panel or specific resources from a specific panel?

I noticed in my installation that it prompts what panel should I use, so I selected the appropriate panel but it still generated the default one which is admin panel.

Thank you in advance!

**Comment by pedro-vasconcelos** [comment]
+1

**Comment by bezhanSalleh** [comment]
i don't think there is away at the moment to support multi panels. but you can generate specific resource policies so look into the generate command it has some options.
