### ISSUE TITLE
question : the package has any user crud interface ?

### ISSUE THREAD

**Issue by quasiperfect** [bezhanSalleh/filament-shield#38]
thanks for your work

did i miss somehow the users management page ?
 
if we need to create it ourselves any example repo i could get inspired by (new with laravel) ?

**Comment by titantwentyone** [comment]
I was directed to this package from https://github.com/3x1io/filament-user which does manage users for Filament so that would be  the package you need (along with this one)

**Comment by quasiperfect** [comment]
thanks @titantwentyone
