### ISSUE TITLE
Support Multitenancy

### ISSUE THREAD

**Issue by KhairulAzmi21** [bezhanSalleh/filament-shield#382]
Any chance we add multitenancy near future ?

**Comment by chiroro-jr** [comment]
Does this support filament multitanency?

**Comment by KhairulAzmi21** [comment]
> Does this support filament multitanency?

not yet.

**Comment by edeoliv** [comment]
Still no support for multi tenant?

**Comment by khalidmaquilang** [comment]
I created a starter app that supports multi-tenant.. you can check it here
https://github.com/khalidmaquilang/tenant-shield

**Comment by mattiadelfranco** [comment]
Why not support the Tenancy for Laravel plugin? I would need too
