### ISSUE TITLE
Can I set custom labels?

### ISSUE THREAD

**Issue by yammycode** [bezhanSalleh/filament-shield#39]
Hi and thanks for the awesome package! 
Q: Can some titles be translated? See picture. 1 - display the resource's $label property. 2 - redefine title in another language. 3 - specify an arbitrary title more understandable to managers. At the same time, do not change the values ​​themselves.
<img width="325" alt="111" src="https://user-images.githubusercontent.com/65212344/166247649-34dc2f5e-fb06-4ce2-8c24-fd480a4d1de7.png">

**Comment by bezhanSalleh** [comment]
not atm 🖖
