### ISSUE TITLE
Resoures in the sub folders accessable by everyone

### ISSUE THREAD

**Issue by wikihadi** [bezhanSalleh/filament-shield#390]
Resoures in the sub folders accessable by everyone
![Screenshot 2024-05-30 010932](https://github.com/bezhanSalleh/filament-shield/assets/4249202/7d748f67-750c-4471-92b0-6fb0cb28182a)
![داشبوردا](https://github.com/bezhanSalleh/filament-shield/assets/4249202/677f0b1d-7b06-42db-a168-1c64d55b0cb1)

**Comment by breizhwave** [comment]
I agree, it's a nice Filament feature to have possibility to use sub folders for Models / Resources, but they won't work with Filament Shield when using subfolders... Any idea how to fix this ? thks

**Comment by AnasSharif** [comment]
I also agree with you in filament docus they mentionds for subdirectories path used AuthServiceProvider but in laravel 11 there's not AuthServiceProvider class.
<img width="864" alt="Screenshot 2024-06-13 at 1 13 17 AM" src="https://github.com/bezhanSalleh/filament-shield/assets/20491569/10c6380a-4c52-46fe-99e0-7875bf7a9b75">

**Comment by aliaxonbaig** [comment]
You can create a provider and extend the AuthServiceProvider

`
<?php

namespace App\Providers;

use Illuminate\Foundation\Support\Providers\AuthServiceProvider;

class CustomAuthServiceProvider extends AuthServiceProvider
{

    protected $policies = [
        'RingleSoft\LaravelProcessApproval\Models\ProcessApprovalFlow' => 'App\Policies\ProcessApprovalFlowPolicy',
        'Spatie\Activitylog\Models\Activity::class' => 'App\Policies\ActivityPolicy',
    ];

    /**
     * Register services.
     */
    public function register(): void
    {

    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        $this->registerPolicies();
    }
}
`

**Comment by yeganehha** [comment]
Hi
According to the changes of Laravel 11 (https://laravel.com/docs/11.x/authorization#manually-registering-policies) and also the documentation of this package (https://github.com/bezhanSalleh/filament-shield?tab=readme-ov-file#custom-folder-structure-for-models-or-third-party-plugins)
, to fix the problem:
Should manually register policies and their corresponding models within the `boot` method of your application's `AppServiceProvider`:

```
use App\Models\Order;
use App\Policies\OrderPolicy;
use Illuminate\Support\Facades\Gate;
 
/**
 * Bootstrap any application services.
 */
public function boot(): void
{
    Gate::policy(Order::class, OrderPolicy::class);
}
```

**Comment by bezhanSalleh** [comment]
it's already mentioned in the docs.

**Comment by webplusmultimedia** [comment]
the problem isn't filament sub-folders resources, it's only models's sub-folders, according with the Laravel doc.
Just add this within the boot method of your application's AppServiceProvider
```php
Gate::guessPolicyNamesUsing(function (string $modelClass) {
    return str($modelClass)
        ->after('Models\\')
        ->prepend('App\\Policies\\')
        ->append('Policy')
        ->toString();
});
```
