### ISSUE TITLE
Seeking Guidance: Centralized Role and Permission Management

### ISSUE THREAD

**Issue by abbasmashaddy72** [bezhanSalleh/filament-shield#392]
Hello,

First off, thank you for creating such an invaluable tool for managing roles and permissions. It's been a great asset to our project.

I am currently trying to find a way to centralize all role and permission management in one place, but it seems this functionality isn't available at the moment. 

Moreover, after enabling all discovery options (`discover_all_resources`, `discover_all_widgets`, `discover_all_pages`) to true, I encountered the following error:
```
Error: Plugin [filament-jobs-monitor] is not registered for panel [admin].
```
This plugin is actually registered in the developer panel.

Additionally, I'm experiencing issues specifically when editing roles. The changes do not seem to reflect as expected, which is causing some disruptions in managing user permissions.

Could you please advise if there is an alternative approach or a workaround to centralize role and permission management? Any guidance on resolving these issues would be greatly appreciated.

Thank you so much for your support and for developing such a helpful tool.

**Comment by bezhanSalleh** [comment]
shield currently doesn't have a way to manage multiple panels. so right now Centralizing it would be too much of a hassle doing it manually but it will have the ability to manage multiple panels to give you a centralize way in near future.

**Comment by abbasmashaddy72** [comment]
Yes, You are correct.

I thought that so after integrating this plugin in my bigger project.

But any why, thanks for the reply.
