### ISSUE TITLE
Clusters are not working properly

### ISSUE THREAD

**Issue by classicalguss** [bezhanSalleh/filament-shield#396]
If a Cluster page has another page within it. Filament Shield will for some reason ignore it, and it won't be listed on the permissions.

Furthermore if you put HasPageShield trait, it won't appear on the navigation, however it can be accessed.

However if a Cluster page had a Resource instead of a Page, then it would work just fine.

**Comment by borex** [comment]
I have the same problem with multiple panels. I have two panels, one for admin and one for users. The admin has a cluster for settings pages and the shield:generate command is not picking it up. In a different project where I had only one panel everything worked fine for me, the generate command is creating permissions for the cluster pages aswell.

**Comment by bezhanSalleh** [comment]
i have been busy with moving. so i'm gonna close this. Please open a new issue with a repro repo.
