### ISSUE TITLE
Svg by name "filament-shield::filament-shield.nav.role.icon" from set "default" not found

### ISSUE THREAD

**Issue by yablochnyi** [bezhanSalleh/filament-shield#397]
'm getting an error: all translations work, but as soon as I switch to 'pl', I get this error. If I move the translations from 'pl' to 'en' and set 'en' in the .env file, everything works fine

**Comment by bezhanSalleh** [comment]
the `pl` translation file might have some miss configuration. unless you are welling to submit a repro rep im closing it for now.
