### ISSUE TITLE
Error with implements FilamentUser and HasPanelShield

### ISSUE THREAD

**Issue by gjimenez-gc** [bezhanSalleh/filament-shield#400]
Hi,

Been trying to setup a `HasPanelShield` `implements FilamentUser` to my User resource but every time I delete the db and try to run the migration from start I'm getting this error: 

` SQLSTATE[HY000] [1049] Unknown database 'laravelfilament02' (Connection: mysql, SQL: select * from `roles` where (`name` = panel_user) limit 1)`

So when the db does not exists and I'm using `implements FilamentUser` its trying to get the roles, thus making the build fail, I'm missing something? 

![image](https://github.com/bezhanSalleh/filament-shield/assets/173948152/ad1d7998-cfba-4e73-90a6-d13ce197297f)

**Comment by nnnnnnnngu** [comment]
set panel user enabled to false
```
'panel_user' => [
        'enabled' => false,
        'name' => 'panel_user',
    ],
```
in `config/filament-shield.php` 

run migration, run `shield:install` and enable panel_user after that.
