### ISSUE TITLE
its asking for premium? Or is this a bug?

### ISSUE THREAD

**Issue by MToffCT** [bezhanSalleh/filament-shield#403]
![Screenshot 2024-07-05 030655](https://github.com/bezhanSalleh/filament-shield/assets/173679078/d7f1d673-4f60-4777-8f3e-8f11876d9587)

![Screenshot 2024-07-05 031135](https://github.com/bezhanSalleh/filament-shield/assets/173679078/dc42c223-810d-4615-9e2d-7bdca88c1fe7)

Kinda lost here....has it moved from a free plugin to a paid/premium plugin by the way?

**Comment by bezhanSalleh** [comment]
Nope still free, might be something with the ide extension you are using
