### ISSUE TITLE
Dashboard widget, pages, Roles resource still visible for `panel_user` without any permissions

### ISSUE THREAD

**Issue by datlechin** [bezhanSalleh/filament-shield#406]
Dashboard widget, pages, Roles resource still visible for `panel_user` without any permissions

<img width="1419" alt="Screenshot 2024-07-14 at 13 54 14" src="https://github.com/user-attachments/assets/8638a314-5f36-4347-9d14-4b036fa19864">

<img width="726" alt="Screenshot 2024-07-14 at 13 54 30" src="https://github.com/user-attachments/assets/a1b77987-378b-4e1b-99f5-5b4ece2dec8c">

<img width="2543" alt="Screenshot 2024-07-14 at 13 54 52" src="https://github.com/user-attachments/assets/9b15e1b8-0464-4c0a-a673-7b1807427cae">

**Comment by chadriae** [comment]
@datlechin You closed this issue but I have the same, how did you fix this?

**Comment by chadriae** [comment]
Okay I found the solution, for anyone who needs it. 

In the filament-shield.php config file edit this line to:
` 'register_role_policy' => [
        'enabled' => true,
    ],`
