### ISSUE TITLE
implement shield authorization in a custom page resource

### ISSUE THREAD

**Issue by gbarrios9670** [bezhanSalleh/filament-shield#410]
I'm sorry for writing in this section, it is clear to me that this section is for reporting issues only, but this is the only option I had to reach you. I just want to know if there is any possibility of implementing authorization on a custom resource page using the shield plugin. I have developed a beautiful application using shield but unfortunately I will not be able to use it if I cannot implement authorization on custom resources pages. I hope you can help me solve this problem, best regards and congratulations for this great plugin.

**Comment by bezhanSalleh** [comment]
Havent joined the filament discord server i take it? If tou have there is a dedicated shield channel.

Anyways, either there or here show me the code for your custom resource's page so I could reference it when advising on how to proceed.

There might be delays in my response here so for quick response I suggest you to join the [filament](https://filamentphp.com/discord) discord server.
