### ISSUE TITLE
General error: 1 no such table: roles

### ISSUE THREAD

**Issue by boralp** [bezhanSalleh/filament-shield#413]
An already installed shield instance fails php artisan migrate command with fresh database. It gives roles table not exists error.

When I commented out createPanelUserRole and then run php artisan migrate everything works fine but without database it is not possible run any php artisan commands with already installed shield instance.

trait HasPanelShield
{
    public static function bootHasPanelShield()
    {
        if (Utils::isPanelUserRoleEnabled()) {

            Utils::createPanelUserRole();

 [internal]:0
      App\Models\User::bootHasPanelShield()

**Comment by bezhanSalleh** [comment]
It's the laravel way and you cannot have or use a logic related to a model whose migration hasn't run yet. so if you want to do `artisan migrate` with any of its (`fresh`,`refresh`) flags, then you need to make sure the `xxxx_create_permission_tables.php` migration runs before the users table.

**Comment by bptik-unw** [comment]
> It's the laravel way and you cannot have or use a logic related to a model whose migration hasn't run yet. so if you want to do `artisan migrate` with any of its (`fresh`,`refresh`) flags, then you need to make sure the `xxxx_create_permission_tables.php` migration runs before the users table.

i have moved create_permission_tables to top but it still give me error 
` SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbname.roles' doesn't exist (Connection: mysql, SQL: select * from `roles` where (`name` = admin) limit 1)`

migrations files:
0001_01_00_000000_create_permission_tables.php
0001_01_01_000000_create_users_table.php

**Comment by abitme** [comment]
> It's the laravel way and you cannot have or use a logic related to a model whose migration hasn't run yet. so if you want to do `artisan migrate` with any of its (`fresh`,`refresh`) flags, then you need to make sure the `xxxx_create_permission_tables.php` migration runs before the users table.

i have moved create_permission_tables to top but it still give me error
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbname.roles' doesn't exist (Connection: mysql, SQL: select * fromroles where (name = admin) limit 1)

migrations files:
0001_01_00_000000_create_permission_tables.php
0001_01_01_000000_create_users_table.php

**Comment by lbitoy** [comment]
Hi @boralp @bezhanSalleh this behaviour also happens when you use a trait on a model (e.g. use haspanelshield) as the model/table isn't created yet, so creation of fresh instances you will encounter this issue. You can check for the table before the model is booted 

eg:   protected static function bootHasPanelShield(): void
    {
        if (Schema::hasTable('roles')) {
            parent::bootHasPanelShield();
        }
    }

**Comment by lbitoy** [comment]
@abitme  @bezhanSalleh @boralp  Just run a check for being in cli only mode (e.g. running migrations, etc.) and ignore

`
  protected static function bootHasPanelShield(): void
    {
        if (app()->runningInConsole()) {
            return;
        }
}
`
