### ISSUE TITLE
Feature: groups among widgets & pages

### ISSUE THREAD

**Issue by GeoSot** [bezhanSalleh/filament-shield#416]
Hello and many thanks for your package. It is really helpful

I would like to ask a question (or a possible feature)

Visiting on the Edit-Role page, we can see a section with the permissions, separated in three tabs (Resources, Pages, Widgets)
The Pages & Widgets tabs list all the available classes using their title (nice till here)

The 'problem' starts in case we have two pages, with the same title, as it gets a bit tricky, to understand who is who.
Is there any option which can help me to group these lists in order to be more user-friendly?
 

In case of pages, the  `$navigationGroup` could be used as default, however for widgets case, I am not sure if they have any group concept, out of the box

The best scenario I have thought to propose, is to provide a hook during names resolving, so each developer be able to customize these names

**Comment by bezhanSalleh** [comment]
Not possible atm.
