### ISSUE TITLE
Resource visible even if the role does not have permissions

### ISSUE THREAD

**Issue by giacomomasseron** [bezhanSalleh/filament-shield#419]
Hi,  
to start using package I create a role ("marketing") and a resource ("Post").

I set no permissions for the role, and I created a user with "marketing" role.

The user can see the Post resource, even if does not have permissions. The Post model uses HasPanelShield trait.

**Comment by valpuia604** [comment]
Did you create Policy.. because it relies on policy in order to work correctly iirc
