### ISSUE TITLE
Failed to open stream: No such file or directory when installing on Windows

### ISSUE THREAD

**Issue by DanielvdSpoel** [bezhanSalleh/filament-shield#42]
Full error: `  file_put_contents(C:\Users\danie\Documents\projecten\laravel-webshop\app\Policies/RolePolicy.php): Failed to open stream: No such file or directory`

Looks like the problems is with the fact i'm using windows. Windows used the \ and this package uses /. Is there a way to fix this?

**Comment by bezhanSalleh** [comment]
this issue was fixed in the last release. which version are you using?

**Comment by pablojnd** [comment]
I have the same problem with
laravel => v9.11
filament => v2.12.13
filament-shield => v1.1.12

**Comment by bezhanSalleh** [comment]
Sorry guys, don't have windows to debug the problem.

If you guys can submit a fix, I can then merge it with next release.

**Comment by Dhruvi289** [comment]
For windows you need to make policy manually by following command :- php artisan make:policy RolePolicy . this would solve your problem
