### ISSUE TITLE
Resource Model Name collision

### ISSUE THREAD

**Issue by zajinx** [bezhanSalleh/filament-shield#421]
I am using Laravel 11.26 and filament-shield 3.2.6 and i stumbled upon some odd behavior. 
I was building a task management app and i have models like, Task, Expense and Resource, the issue pops up if you have a model called Resource you won't be able to edit roles properly, when you open the page the form won't be filled out. the problem went away as soon as i changed the name of the model to MyResource.

<img width="950" alt="image" src="https://github.com/user-attachments/assets/21f9765a-39cc-4695-bcb7-3d71d3056daf">

![image](https://github.com/user-attachments/assets/cda7ad67-dfe2-4777-a563-bc75bf61bf8b)

**Comment by bezhanSalleh** [comment]
guess, you already have your answer then! 🍻
