### ISSUE TITLE
I could not open discussion

### ISSUE THREAD

**Issue by zsoltjanes** [bezhanSalleh/filament-shield#422]
Hi guys!

I wanted  to createa discussion "Ask help" but it drops me 404 page not found
https://github.com/bezhanSalleh/filament-shield/discussions/new?category=q-a

I would like to create custom not page and resource based permission like view block on the frontend or like allow user to  visit horizon page, how is it possible with your package?

Thanks for the help, 

Zsolt

**Comment by bezhanSalleh** [comment]
Shield is a wrapper around spatie so you can always create permissions using the `php artisan permission:create-permission <name> [<guard>]` or through a seeder etc. Any permission that is not related to a filament component/entity (resources, pages, widgets) will be listed on the `Custom Permissions` tab of shield's `RoleResource`. Mind you, if you change a components name or model while permissions are generated before hand; those will become orphans and will be listed as custom permissions.

**Comment by lukasinko** [comment]
@bezhanSalleh I've run eg. `php artisan permission:create-permission create_web` and i don't see it listed under `Custom Permissions`, what am i doing wrong ? Thank you

**Comment by bezhanSalleh** [comment]
Make sure the custom permissions is set to true from the config first
https://github.com/bezhanSalleh/filament-shield/blob/3.x/config/filament-shield.php#L56C9-L56C39

**Comment by lukasinko** [comment]
@bezhanSalleh Thank you, i can confirm it works.

**Comment by bezhanSalleh** [comment]
Your question kinda confused me at first, caz I thought you meant you have already enabled it but yeah, enabling it will list custom permissions.

**Comment by lukasinko** [comment]
I've just missed that config property. Thank you again.
