### ISSUE TITLE
Wrong check for uniqueness

### ISSUE THREAD

**Issue by Udaberrico** [bezhanSalleh/filament-shield#423]
Hey there,

I stumbled upon this small issue. I am starting to integrate a filament panel into an existing application with multiple guards for web and api. The roles share mostly the same name and differ by guard_name. For the Spatie Permission Package this is no problem, name and guard_name aren't unique in the database.

Now, when I try to update a role with your plugin, I get stuck because of a unique check on the name of a role. Is there a special reason for this?

https://github.com/bezhanSalleh/filament-shield/blob/a71ca76f89fbf5faaca39bf0db6a00c12ffecab2/src/Resources/RoleResource.php#L47

**Comment by bezhanSalleh** [comment]
Right now, the solution is to publish the resource and change the uniqueness check however you want. `php artisan shield:publish`.
