### ISSUE TITLE
duplicate queries by getNavigationBadge()

### ISSUE THREAD

**Issue by AshrafBasry** [bezhanSalleh/filament-shield#427]
This issue is related to #326 
php: 8.3.12
Filament: 3.2.118
filament-shield: 3.2.6

![bug1](https://github.com/user-attachments/assets/9f5d6f8b-ed08-4c94-b0f7-605df628d3f2)
and here is the stack trace with Xdebug
![bug2](https://github.com/user-attachments/assets/ed4b6bef-c4cc-4a04-b138-c39aa5d24c34)
![bug3](https://github.com/user-attachments/assets/a7bec7a5-91cf-4ef6-a0db-f7da6a82c030)

It all happen at this filament file
`vendor/filament/filament/resources/views/components/layout/index.blade.php`
line 4
`$navigation = filament()->getNavigation()`
line 83
`@if (filament()->hasNavigation())`

#notice: It only happen on the initial route request but not for livewire update request like the one you posted on the previous issue https://github.com/bezhanSalleh/filament-shield/issues/326#issuecomment-1913548398

**Comment by bezhanSalleh** [comment]
As you can see from the trace stack this isn't a shield issue, turn on badge for any other resource and it will be the same. I don't remember when but I think the team has given a response regarding this so you might wanna checkout the closed issues there related to the badge duplicate query.
