### ISSUE TITLE
Authorizations not working in different nav group

### ISSUE THREAD

**Issue by akiftezcan38** [bezhanSalleh/filament-shield#428]
When I move the page to a different nav group, the authorization for that page does not work. But when I remove the nav group on the page, the authorization works. 

![image](https://github.com/user-attachments/assets/0ce26f7c-b3da-4a9f-8a3a-0fb3eea2c976)

![image](https://github.com/user-attachments/assets/5dd68e83-864d-486d-bd1b-f30a075dfd33)

but when I remove the nav group, the button comes or does not come according to authorization.

When I add the page to the nav group, it comes blank and the button does not appear as in the picture

Can you help me?

**Comment by bezhanSalleh** [comment]
i'm not sure by `page` what you mean? so could you submit a minimum reproduceable repo and will take a look at it.
