### ISSUE TITLE
Problem with Polish Language - Error: Svg by name "filament-shield::filament-shield.nav.role.icon" from set "default" not found.

### ISSUE THREAD

**Issue by SebastianRajca** [bezhanSalleh/filament-shield#430]
The name of the translation file in Polish includes an underscore instead of a dash.

![image](https://github.com/user-attachments/assets/6467087f-b483-4724-bb5e-cbe3c6362650)

This causes this error if set
APP_LOCALE=pl 
APP_FALLBACK_LOCALE=pl  

![image](https://github.com/user-attachments/assets/0704e667-08cb-402d-b381-34996679a42b)

**Comment by bezhanSalleh** [comment]
fyi... next time in any repo plz search the closed issues before creating one. That way you might get your answer faster.
#315 
#320
