### ISSUE TITLE
shield:generate is not generating any policies only permissions

### ISSUE THREAD

**Issue by bardolf69** [bezhanSalleh/filament-shield#434]
I've just recently installed Shield on my filament project and after running shield:generate it created all of the permission but no policies, so the permissions are having no effect.

**Comment by bardolf69** [comment]
nevermind I found I needed to run ```php artisan shield:generate --all``` and that solved the problem.

**Comment by Werffios** [comment]
Hi, I had the same issue and struggled for hours. I knew it was related to the policies but didn't want to create them manually. This should definitely be included in the official documentation. Thank you so much for sharing your solution, it was very helpful.
