### ISSUE TITLE
permissions management by user

### ISSUE THREAD

**Issue by Etzahu** [bezhanSalleh/filament-shield#435]
Is there a way that a user can only manage the permissions of certain models and not all of them?

**Comment by bezhanSalleh** [comment]
not atm...

**Comment by DiegoRicardoValdiviaArreola** [comment]
I found a way. But don't know if is correct:
First I published the RoleResource 
`shield:publish`
And then modified these two methods in the RoleResource file: 

- `public static function getResourceEntitiesSchema(): ?array`
- `public static function getResourceTabBadgeCount(): ?int`

To edit the filament shield resources based on user role:
```
public static function getResourceEntitiesSchema(): ?array
    {
        $filemantShieldResources = FilamentShield::getResources();
        if(!auth()->user()->hasRole(config('system.roles.super_admin')))
        {
            unset($filemantShieldResources['company']);
        }

        return collect($filemantShieldResources)
            ->sortKeys()...

```
