### ISSUE TITLE
Role to allow user creation, but not assign super_admin

### ISSUE THREAD

**Issue by mpltr** [bezhanSalleh/filament-shield#437]
I've got an application up and running with shield and a User Resource where I can create new users. I'd like to be able to create a Role, let's call it Editor, where the users assigned to that role cannot edit existing user records but can create new users. This works out of the box, the problem is, there is nothing to stop them from creating a super_admin, or a user with greater control and then using that account for full access. 

So my question is, can you restrict the roles that particular role can assign when creating a new user?

**Comment by rolland97** [comment]
You can modify the query in the select options

`
 Forms\Components\Select::make('roles.name')
    ->multiple()
    ->relationship(
        name: 'roles',
        titleAttribute: 'name',
        modifyQueryUsing: function (Builder $query) {
            if (! Auth::user()->isAdmin()) {
                return $query->whereNot('name', config('filament-shield.super_admin.name'));
            }
        }
    )
`

with the use of modifyQueryUsing you can filter out the roles.

**Comment by mpltr** [comment]
Thanks @rolland97. The isAdmin method doesn't appear to exist when using :

`use HasRoles;`

in the User model. Presumably the isAdmin method must be added to the User model. Something like:

` public function isAdmin(): bool
    {
        return $this->hasRole(config('filament-shield.super_admin.name'));
    }`
   
   ??

**Comment by bezhanSalleh** [comment]
@mpltr that's just a method on the your auth model
```php
public function isAdmin()
{
    return $this->hasRole(config('filament-shield.super_admin.name'));
}
```
