### ISSUE TITLE
Problems installing when using Ulid as user id

### ISSUE THREAD

**Issue by noookeee** [bezhanSalleh/filament-shield#439]
My user model uses Ulids. Maybe I made a general mistake, but during the installation of the plugin I got the following error message:

```
Illuminate\Database\QueryException
SQLSTATE[01000]: Warning: 1265 Data truncated for column ‘model_id’ at row 1 (Connection: mysql, SQL: insert into `model_has_roles` (`model_id`, `model_type`, `role_id`) values (01jby0nkvew5w64e5v8j3eh1ec, App\Models\User, 1))
```

The model_id field is a BIGINT field after installation, but for Ulids it must be a varchar field. I changed the field type and then the installation worked perfectly.

**Comment by bezhanSalleh** [comment]
not a shield issue, you can find out how to set the core package using Ulids https://spatie.be/docs/laravel-permission/v6/advanced-usage/uuid
