### ISSUE TITLE
Issue with Filament Shield Plugin – Missing Roles Table During Migration

### ISSUE THREAD

**Issue by ali-hasnain-dev** [bezhanSalleh/filament-shield#442]
Hello,

Hello,

I hope you're doing well.

I'm encountering an issue when using the Filament Shield plugin. Specifically, when the database is empty and I attempt to run the php artisan migrate command, I receive the following error:

**SQLSTATE[42S02]: Base table or view not found: 1146 Table 'aincollection.roles' doesn't exist (Connection: mysql, SQL: select * from `roles` 
where (`name` = user) limit 1)**

It appears the roles table is missing, and the migration is failing as a result. I've attached screenshots for your reference.

Could you please help me resolve this issue?

Thank you in advance for your assistance.

![image](https://github.com/user-attachments/assets/1454ef74-fba6-4049-bdac-8fe2aef28633)

![image](https://github.com/user-attachments/assets/87802320-bf6b-41f7-947d-6f8c9697bbc6)

![image](https://github.com/user-attachments/assets/8643bcc5-e981-40b6-9ceb-aaa75dd0951a)

**Comment by bezhanSalleh** [comment]
make sure you have run the `shield:install` command
