### ISSUE TITLE
shield:install admin not working properly

### ISSUE THREAD

**Issue by arielsegumpan** [bezhanSalleh/filament-shield#443]
I run the php artisan shield:install admin it generate this 
````
->plugins([
           ;
    }
}

use BezhanSalleh\FilamentShield\FilamentShieldPlugin;
])
    FilamentShieldPlugin::make(),
````
    

instead of
`    ->plugins([
        \Bezhansalleh\FilamentShield\FilamentShieldPlugin::class,
    ])`
    
  it mess the AdminPanelProvider.php

**Comment by aphoe** [comment]
I am having the same problem. Yes, I am using windows

**Comment by zwei-c** [comment]
I have the same issue.

I’m using Laravel Herd on Windows 11 and initialized a new Laravel 11 project (without any starter kits), only installing Filament and Shield.

Running php artisan shield:setup works fine, but I encounter an issue only when running php artisan shield:install admin, resulting in the same outcome as @aphoe: an AdminPanelProvider.php file is generated in app/Providers/filament/.

Can someone help me resolve this issue?


![image](https://github.com/user-attachments/assets/676bceb0-01f6-4b7f-ba73-7e59606e8b83)


![image](https://github.com/user-attachments/assets/9ce8a0f2-77ea-4421-ab76-2d44c80701af)

**Comment by arielsegumpan** [comment]
for windows 11, I manually  insert the shield plugin

 
```

use BezhanSalleh\FilamentShield\FilamentShieldPlugin;


->plugins([

                FilamentShieldPlugin::make()
                
 ]);
```` 
 
  and it work like a charm.

**Comment by bezhanSalleh** [comment]
i think the windows filesystem kinda misses up everything and i don't have windows to test it. but the doc is updated on how to do it manually.

**Comment by aphoe** [comment]
> i think the windows filesystem kinda misses up everything and i don't have windows to test it. but the doc is updated on how to do it manually.

I checked the command for `shield:install`, it had this statement towards the end.

```
 $this->call('shield:generate', [
            '--resource' => 'RoleResource',
            '--panel' => $panel->getId(),
        ]);
```
