### ISSUE TITLE
shield:setup assumes our auth model is User.

### ISSUE THREAD

**Issue by Saifallak** [bezhanSalleh/filament-shield#451]
**Describe the bug**
Following readme, first thing after composer require is running `shield:setup` and getting this error:
   ERROR  Please make sure your Auth Provider model (\App\Models\User) uses either `HasRoles` or `HasFilamentShield` trait.  

**Expected behavior**
should be a way to specify other auth model.
or just in readme we should say to publish config first.

**please complete the following information:**
 - OS: Windows
 - Filament 3.2.15
 - Version 3.3

**Comment by bezhanSalleh** [comment]
This is sorta bug, will fix in the next release but for now the instructions are updated.
As for allowing multi auth provider models, i don't really have the time to put into it atm.
