### ISSUE TITLE
make guard select, and configured through config file

### ISSUE THREAD

**Issue by Saifallak** [bezhanSalleh/filament-shield#452]
can we make guard select?, and maybe their options are retrieved from config?

![image](https://github.com/user-attachments/assets/1c5933d1-a659-45c4-8625-8abcb0ccb126)

because every time I use this plugin I have to publish resource and just make it hardcoded 'admins' or 'web' or whatever.

**Comment by bezhanSalleh** [comment]
The configuration/customization of the resource is too broad and it depends on the dev's perefernce and app's requirements. Since shield can encompass every situation, I have made the `shield:publish` command more intuitive to provide the freedom required to configure it as the need arises.
