### ISSUE TITLE
Non-static method called statically (configurePermissionIdentifierUsing)

### ISSUE THREAD

**Issue by arturafonsoaa** [bezhanSalleh/filament-shield#456]
**Describe the bug**
When using the package with newer PHP versions, such as PHP 8.3, the following error occurs: `Non-static method BezhanSalleh\FilamentShield\FilamentShield::configurePermissionIdentifierUsing() cannot be called statically`. This happens because the method configurePermissionIdentifierUsing() is not declared as static but is being called statically in the code.

**To Reproduce**
1. Add the `FilamentShield::configurePermissionIdentifierUsing(...);`
2. Open the project on the browser

**Expected behavior**
The method configurePermissionIdentifierUsing() should either be declared as static or called through an instance to avoid compatibility issues with PHP 8.3.

**Screenshots**
![image](https://github.com/user-attachments/assets/69e75612-7247-4c49-a92b-b71e0114013d)

**please complete the following information:**
 - OS: Ubuntu 22.04
 - Filament 3.2.128
 - Version of Shield 3.3.4
 - PHP 8.3

**Comment by bezhanSalleh** [comment]
Wrong import there mate, should be called on the facade.
`use BezhanSalleh\FilamentShield\Facades\FilamentShield;`
