### ISSUE TITLE
"php artisan shield:setup --tenant=App\Models\Team" messing up with project

### ISSUE THREAD

**Issue by agharium** [bezhanSalleh/filament-shield#458]
After updating the package and also updating Laravel itself (10 to 11), upon ```running php artisan shield:setup --tenant=App\Models\Team``` on my main project, I first had the following error:

```
In Container.php line ***:

  Target class [cache] does not exist.

In Container.php line ***:

  Class "cache" does not exist
```
  
Couldn't find a fix for that error, had to start from scratch on a brand new project, lots of copying and pasting - but no problem, I thought the guilty was me, messing up by updating Laravel on an on-going project.

But after running ```php artisan shield:setup --tenant=App\Models\Team``` on the brand new project I get the same error. Then, I checked the ```filament-shield``` documentation (more) carefully and it said that it required ```spatie-permission``` installed. I've worked with ```filament-shield``` and installed it manually, always tought it was automatically installed along with the package, but ok. Started a new project, ```spatie-permission``` installed first.

Now after running ```php artisan shield:setup --tenant=App\Models\Team``` my ```config/``` files ```filament-shield.php``` and ```permission.php``` became both blank except for the line ```187``` on ```pemission.php```: ```'teams' => true``` - the other 186 lines are completely blank. And, of course, getting ```Target class [cache] does not exist.``` on each console command.

Anyone going through this kind of issue? I was specially eager (and I still am!) to try out the new filament-shield version on my current project.

Thanks !

**please complete the following information:**
 - OS: Windows 10 22H2 (good old powershell)
 - Filament 3.2
 - Laravel 11

**Comment by bezhanSalleh** [comment]
from the looks of it, the issue is with the upgrade and the cache store setup. since laravel 11 uses database as the cache store and if you have migrated to that then you have to properly set it up. if in your `.env` you have something like `CACHE_STORE=database` then run the following 
```php
php artisan make:cache-table
 
php artisan migrate
```
or change it to `CACHE_STORE=file`

**Comment by youssefdegweyy** [comment]
I have the same issue with fresh new laravel 11 project on windows 10, cant quite fix it? the cache table already exists in the initial migrations so I dont know how to fix it

**Comment by agharium** [comment]
Hey.

I ended up not running the specified commands and dropped the `CACHE_STORE=database` idea and went for g'old `CACHE_STORE=file` which just works. I also ran the normal commands and manually set the tenant options on the `filament-shield.php` and `permission.php` config files. The new tenant commands were giving me headache.

Ah, and after configuring everything don't forget the `php artisan shield:generate --all && php artisan shield:super-admin --tenant=1` commands :)

**Comment by jeffegiovani** [comment]
For me, the workaround for this issue was deleting the `config/filament-shield.php` then execute the `php artisan shield:setup --tenant=App\Models\RealEstate` command.

The instalation process caused many bugs, but i solved they're manualy one-by-one.

But now, the creation processes dont assign the Role to Tenant.
The `team_id` column always be null at `roles` table.

Any ideias to solve this problem?

**Comment by CyberPunkCodes** [comment]
For anyone who stumbles here and wants a current working solution, I lay out the steps in my issue. If you have not ran any of the commands yet, you can manually run all of the things necessary. Check out issue #513
