### ISSUE TITLE
Filament Shield: Menu Not  Appears In Web

### ISSUE THREAD

**Issue by Egi-Pebriyawan** [bezhanSalleh/filament-shield#460]
i have read and following the steps of installing filament shield, but why menu filament shield not appears in my website ? 
![image](https://github.com/user-attachments/assets/01563203-3497-4af1-a8c3-4c19a93b13e9)

**Comment by lhonay** [comment]
Did you get it?

**Comment by Egi-Pebriyawan** [comment]
No i dont get it Sir. i follow exactly the steps 1 to 4. I just have 1 user but why the user cannot have super_admin roles.

**Comment by bezhanSalleh** [comment]
answered in #453. search the issues and then create and issue if don't find the solution.
