### ISSUE TITLE
Name validation unique per tenant

### ISSUE THREAD

**Issue by galliroberto** [bezhanSalleh/filament-shield#461]
**Describe the bug**
Name validation unique is per table, not per tenant

```php
->unique(ignoreRecord: true)
                                
->unique(config('permission.table_names.roles'), 'name', null, 'id', function($rule){
    return $rule->where(app(PermissionRegistrar::class)->teamsKey, Filament::getTenant()->getKey());
})
```

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the 'name' field in the form schema to use tenant-specific validation for uniqueness. This ensures that role names are unique per tenant rather than globally.

You can review changes in this commit: https://github.com/mnmnk43434/bezhanSalleh-filament-shield-461/commit/1c7eabb73a3910acd02c169abae8ffa887d78c9c.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by bezhanSalleh** [comment]
> **Describe the bug** Name validation unique is per table, not per tenant
> 
> ```
> ->unique(ignoreRecord: true)
>                                 
> ->unique(config('permission.table_names.roles'), 'name', null, 'id', function($rule){
>     return $rule->where(app(PermissionRegistrar::class)->teamsKey, Filament::getTenant()->getKey());
> })
> ```

this isn't an issue per se, as others might combine the unique validation with guard when using multiple guards. I left it as is becuase you can publish the resource and handle any sort of customization you want.

**Comment by galliroberto** [comment]
Thanks for your reply.

I publish resource, how to override yours?

**Comment by bezhanSalleh** [comment]
if published it, then you know where you have published it so it will be just like any other resource in your codebase so you don't really have to override anything that's kinda the point of publishing the resource.have more question, ask in the filament discord server's shield channel. might even find other info to other questions without waiting for something trivial like this.

**Comment by jgmuchiri** [comment]
@galliroberto did you resolve this? Seems the override is not working on my end either. The override is supposed to occur in the `register` method of  `FilamentShieldPlugin` 
```php
public function register(Panel $panel): void
    {

        if (! Utils::isResourcePublished($panel)) {
            $panel->resources([
                Resources\RoleResource::class,
            ]);
        }
    }
```
I have `RoleResource` in `App\Filament\Resources` which is then published and based on this logic it is supposed to override the package RoleResource but it ignores mine altogether.

**Comment by bezhanSalleh** [comment]
> @galliroberto did you resolve this? Seems the override is not working on my end either. The override is supposed to occur in the `register` method of `FilamentShieldPlugin`
> 
> ```
> public function register(Panel $panel): void
>     {
> 
>         if (! Utils::isResourcePublished($panel)) {
>             $panel->resources([
>                 Resources\RoleResource::class,
>             ]);
>         }
>     }
> ```
> 
> I have `RoleResource` in `App\Filament\Resources` which is then published and based on this logic it is supposed to override the package RoleResource but it ignores mine altogether.

do you guys actually read! you no longer need to override anything!!! just publish the resource `shield:publish panelid`.

**Comment by jgmuchiri** [comment]
@galliroberto got it working with `php artisan shield:publish` (you might need to add panel id if using multiple). Then you can modify the RoleResource in App\Filament\Resources

**Comment by galliroberto** [comment]
I am building an app with module (plugins).

So I hide shield from config

```php
return [
    'shield_resource' => [
        'should_register_navigation' => false,
```

and register my plugin where override your resource.

```php
->plugins([
                FilamentShieldPlugin::make()->gridColumns([
                    'default' => 1,
                    'sm' => 2,
                    '2xl' => 3
                ])
                    ->sectionColumnSpan(1)
                    ->checkboxListColumns([
                        'default' => 1,
                        'sm' => 2,
                        'lg' => 3,
                        'xl' => 4,
                    ])
                    ->resourceCheckboxListColumns([
                        'default' => 1,
                        'sm' => 2,
                    ]),
                RoleAndPermissionPlugin::make(),
            ])
```

Thanks to all.
