### ISSUE TITLE
Add shield to `NavigationItem`

### ISSUE THREAD

**Issue by bilogic** [bezhanSalleh/filament-shield#469]
**Is your feature request related to a problem? Please describe.**

I have `NavigationItem`s that lead to other panels, possible to extend shield coverage to them?

**Describe the solution you'd like**
Able to show/hide `NavigationItem` using filament-shield

**Describe alternatives you've considered**
Could not think of any

**Additional context**
N/A

**Comment by bezhanSalleh** [comment]
if you mean the navigation items' visibility then you would need custom permissions for those or base your logic on the existing resource related permissions. if you mean to handle multiple panels, then it's not supported outta the box unless you alter it. these are questions search the help or shield channel on filament discord for more info.

**Comment by bilogic** [comment]
It was more a feature request rather than a question as I do know how to code what I needed, but it was cumbersome, that's why I asked. Thanks.

**Comment by redfieldchristabel** [comment]
Hi there, Using a custom permission is quite nice solution, but how to make a custom permission also list on role resource?. Right now only generated permission are show in role's edit  serouce page?
