### ISSUE TITLE
shield:generate - Enable "exclude" by default

### ISSUE THREAD

**Issue by a-zog** [bezhanSalleh/filament-shield#48]
Hi,

First of all, thank you for this amazing plugin.

I suggest enabling exclude by default (or at least display a warning + prompt for existing Policies) because it may override custom rules.

Keep up the great work 🎉

**Comment by bezhanSalleh** [comment]
tnx for the kind words... we'll see about improvements in july... but in the mean time:

1. install
2. configure
3. run shield commands

Because, once you have your preferred config setup you won't make daily or weekly updates to the sections of your app like Shield.
