### ISSUE TITLE
Problem with custom permissions

### ISSUE THREAD

**Issue by jals-es** [bezhanSalleh/filament-shield#51]
Hello, I'm trying to add a custom permission `import` only to a specific entity `project`. 

The problem is when I add this permission to prefixes > resource array, the permission is added to all entities.

```
'prefixes' => [
        'resource' => [
            'view',
            'view_any',
            'create',
            'delete',
            'delete_any',
            'update',
            'import'  //custom permission
        ],
        'page'  =>  'view',
        'widget' => 'view'
    ],
```

How can I add this `import` permission to only `project` entity? Is that possible?

**Comment by bezhanSalleh** [comment]
if you add a permission it will be created for as many resources as you have.
to address your situation  enable `Custome Permissions` tab from the shield Settings page and then, create one-off permissions via:
```bash
php artisan permission:create-permission 'your_custom_permission_name`
```
