### ISSUE TITLE
How attribute a role on a user ?

### ISSUE THREAD

**Issue by eaziweb95** [bezhanSalleh/filament-shield#57]
Hi all

I installed the filament shield plugin after following the instructions on https://github.com/bezhanSalleh/filament-shield
The role management is well integrated but i don't know how i can attribute a role on users.
There is no explanation on how associate a role on user except

Add the Spatie\Permission\Traits\HasRoles trait to your User model(s):
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
use HasRoles;
//.....
}
![roles](https://user-images.githubusercontent.com/58070424/177339190-7ca80977-701b-4ce0-a1de-0119f3038275.jpg)
![users](https://user-images.githubusercontent.com/58070424/177339214-0584425a-85bd-42e1-820f-72b86c38a6d3.jpg)

**Comment by eaziweb95** [comment]
Thanks for your reply

**Comment by eaziweb95** [comment]
I've inserted manually the records in the model-has-roles table but it is not a solution

**Comment by eaziweb95** [comment]
is there anybody which follows this plugin ??

**Comment by Z3d0X** [comment]
You can create a UserResource, and add roles field as a relationship multi select

**Comment by HugoGanoza** [comment]
- Run 
`php artisan make:filament-relation-manager UserResource roles name`

- app\Filament\Resources\UserResource\RelationManagers\RolesRelationManager.php
```
            ->headerActions([
                ............
                Tables\Actions\AttachAction::make(),
            ])
            ->actions([
                ............
                Tables\Actions\DetachAction::make(),
            ])
```

- app\Models\User.php
```
    public static function getRelations(): array
    {
        return [
            RelationManagers\RolesRelationManager::class,
        ];
    }
```

**Comment by bezhanSalleh** [comment]
as everybody else said, Shield only takes care of roles and permissions generation. Role or Permission association is totaly up to the dev because you can either give a user a role or a permission via role or direct permission so handling those scenarios is totaly up to you...

**Comment by eaziweb95** [comment]
I have this message Command "make:filament-relation-manager" is not defined
I'm on filament 2.0
I think that the method getRelations() is rather in UserResource.php
Which method is added in Models\User.php ?
