### ISSUE TITLE
Password is not hashed when create/update 

### ISSUE THREAD

**Issue by zaheen** [bezhanSalleh/filament-shield#58]
I install this package and created/updated a user via admin panel, but password is just plain text when saved???

**Comment by bezhanSalleh** [comment]
Shield does not manage User resource.... it only manages automatic permission generation and role resource.
how you associate and create your user is up to you. 
to solve your problem take a look at breezy and https://github.com/jeffgreco13/filament-breezy or https://github.com/3x1io/filament-user

**Comment by zaheen** [comment]
Thanks for the explanation ...
