### ISSUE TITLE
(IDEA) Greater freedom to generate permissions

### ISSUE THREAD

**Issue by luilliarcec** [bezhanSalleh/filament-shield#59]
I think that more than once we have collided with the possibility that not all our resources share the same ones, many times some have less and others more permissions than those we have already defined.

We could give developers a little more freedom, if we define a function through an interface so that the permissions that the resource will have are written there.

I'm currently working on it, since most of my projects need them and I don't really like the idea of ​​having custom permissions. Not when view_role, view_any_role and more are inside the same segment but disable_role will be outside the Role segment just because it is different.

I don't know if you'd be interested in me opening a PR when I'm done setting this up in my project.

**Comment by bezhanSalleh** [comment]
Submit your PR and I will see if we can make it work with the package by default or as an option so the devs can opt in/out.
