### ISSUE TITLE
It generates policies without using guard

### ISSUE THREAD

**Issue by cobraprojects** [bezhanSalleh/filament-shield#62]
I have two guards `web` for frontend for `User` model and `admin` guard for filament for `Admin` model.

So in `filament.php` config file I have:
```
'auth'   => [
        'guard' => env('FILAMENT_AUTH_GUARD',  'admin'),
        'pages' => [
            'login' => \Filament\Http\Livewire\Auth\Login::class,
        ],
    ],
```
when I  use `php artisan shield:install` or generate from the admin panel it generates the policies for the default gaurd not for the filament guard

**Comment by bezhanSalleh** [comment]
it's not the guard actually, it's the default `User` model.
Which has been hardcoded in the `DefaultPolicy` stub.
It's on my todo list to make it configurable via settings page, but haven't gotten to it yet.
So either make a PR or wait another week or so.

And to Solve your current Problem you would need to update the `DefaultPolicy` to use `App\Models\Admin` then run the `shield:generate` command.
