### ISSUE TITLE
Missing Permissions

### ISSUE THREAD

**Issue by intrepidws** [bezhanSalleh/filament-shield#71]
Currently, the DefaultPolicy stub has methods for the following:

- viewAny
- view
- create
- update
- delete
- deleteAny

By default, when using the `--model` flag, Laravel policies also contain methods for:

- restore
- forceDelete

Additionally, Filament also looks for the following policy methods:

- forceDeleteAny
- replicate
- restore
- restoreAny

I'd love to PR the addition of these other six methods by default, along with default model permissions for each. Would you be open to this?

**Comment by bezhanSalleh** [comment]
fixed in #69 but feel free to PR something if you think its worth implementing.
