### ISSUE TITLE
Getting 500 error on all shield pages except index page

### ISSUE THREAD

**Issue by dev-chahal** [bezhanSalleh/filament-shield#75]
Hi, I am using this package for roles and permissions. It was working absolutely fine but now it is throwing 500 error on all pages of the shield except the index page. I am able to see a list of roles and nothing else.

Also, I am unable to debug it as well. It is not showing any error even after enabling the debug mode.

<img width="1273" alt="Screenshot 2022-07-21 at 6 12 01 PM" src="https://user-images.githubusercontent.com/91047757/180216755-a195642c-2133-47be-85f3-479b9deb179f.png">

**Comment by bezhanSalleh** [comment]
well, no specific error so will be hard to know but should be fixed in #69 ... will be out be the weekend
