### ISSUE TITLE
Cannot Change Page and Widget Permission Prefixes

### ISSUE THREAD

**Issue by intrepidws** [bezhanSalleh/filament-shield#76]
I have tried changing the widget and page permission prefixes to several different things (`access_page`, `view_page`, `page_view`, etc). Changing to anything at all results in a `Class "" not found` error when trying to access a role view or update page.

**Comment by bezhanSalleh** [comment]
it's likely you are using some other package which provides widgets because the thrid-party package page issue is resolved only the widgets are the same... which will be resolved in the next release...
