### ISSUE TITLE
 Method Illuminate\Support\Stringable::toString does not exist. 

### ISSUE THREAD

**Issue by asefsoft** [bezhanSalleh/filament-shield#77]
It seems `toString ` is not a function in this set of packages:

```
bezhansalleh/filament-shield      v2.0.4
filament/filament                 v2.14.4
laravel/framework                 v8.83.21
spatie/laravel-permission         5.5.5
```

route:
`/shield/roles/settings`

file:
`\BezhanSalleh\FilamentShield\Resources\RoleResource\Pages\ViewShieldSettings::getFormSchema():54`
and also here:
`\BezhanSalleh\FilamentShield\FilamentShield::getResources():104`

I dont know about this `toString()` function but it seems there is no such function in my `Stringable `class

**Comment by bezhanSalleh** [comment]
aha, seems that laravel 8 doesn't have the `->toString()` method...
will look into a fix
