### ISSUE TITLE
Widgets defined in sub folder cause exception to the package

### ISSUE THREAD

**Issue by asefsoft** [bezhanSalleh/filament-shield#78]
I have a sub folder on my widgets directory to organize widgets. Then i realized bcoz of that, your package can not do its job which i will explain why:

My widgets are something like:
![image](https://user-images.githubusercontent.com/46367425/180407744-07ede062-da17-4dd3-a558-4761e281232d.png)

in 
`\BezhanSalleh\FilamentShield\Resources\RoleResource::getWidgetEntityPermissionSchema()`
you call 
`FilamentShield::getLocalizedWidgetLabel($widget)`
then bcoz of sub folder, value of $widget would be something like `_my_sub_folder_surveys_report_overview`
then in `transformClassString()` function you can not find class name and return empty string, then in this call
        `$parent = get_parent_class($class);`
$class would be empty and cause this nice exception:
` get_parent_class(): Argument 1 ($object_or_class) must be an object or a valid class name, string given `

I think you should consider such situations.
Thanks

**Comment by bezhanSalleh** [comment]
fixed in #69 ... will be out be the weekend
