### ISSUE TITLE
Filament Shield permissions are not applying on some pages

### ISSUE THREAD

**Issue by mnafullstack** [bezhanSalleh/filament-shield#79]
I've installed laravel 9.x version with filament, filament-shield, spatie laravel-permission, filament blog, and some other packages. Everything is working fine but the filament shield permissions are not working correctly. 

This is my normal user role settings and I have disabled all permissions to the normal user role except the dashboard page, but the user can still see all the pages in his account except the "Roles" and "Users" pages. the permissions are just implemented on these two pages, the rest of the pages are still showing in the user account.

https://www.linkpicture.com/q/filament.png

What can be the issue, I've installed all the packages with the documentation given on the packages documentation page?

**Comment by bezhanSalleh** [comment]
checkout the readme for https://github.com/bezhanSalleh/filament-shield#pages enforcing `page` level permissions.

**Comment by mnafullstack** [comment]
Hi bazhanSalleh, thank you very much for your response. I have tried to set permissions using HasPageShield trait in the pages but If I apply this trait, all users cannot access this trait applied pages.

**Comment by mnafullstack** [comment]
And I will be waiting for "brings some quality of life imporvements" to be published in the main package. Thank you.

**Comment by Tushar4343** [comment]
i tried all settings not working. also not hide from navigation and also no permission still normal user access to delete record even force delete also do. please fix these problems or make video on that topic & upload on YouTube.

**Comment by Tushar4343** [comment]
old version is awesome and definitely better. setting menu is really help full

**Comment by bezhanSalleh** [comment]
Not clear on your issue, setting was an extra step that felt kinda redundant so I removed it, so if you still have an issue ask it on discord instead of commenting on closed issues. Ppl on discord can get you an answer faster than here.
