### ISSUE TITLE
Empty permision list for resources

### ISSUE THREAD

**Issue by asefsoft** [bezhanSalleh/filament-shield#80]
Hello
I just updated from v1 to v2 but I have a problem.
In Edit page of a Role, there is no permissions to be selected for resources:
![image](https://user-images.githubusercontent.com/46367425/180448304-74c02fed-2cbf-41d0-a411-6c819a787697.png)

**what did I wrong?**

**Comment by bezhanSalleh** [comment]
as I said in your previous issue, all of this will be fixed in #69  and will be released by the weekend.
so please stop creating issues.

**Comment by bezhanSalleh** [comment]
as I said in your previous issue, all of this will be fixed in #69  and will be released by the weekend.
so please stop creating issues.

**Comment by asefsoft** [comment]
> as I said in your previous issues, all of this will be fixed in #69 and will be released by the weekend. so please stop creating issues.

Hi
This issue is not related to those other issues.
I found the problem:
I am using spatie/laravel-multitenancy package and it is needed to be boot before your package. bcoz in your provider while booting, you are checking for existence of `filament_shield_settings` table and if your package is boot before multitenancy then there is no valid database connection and your package thinks there is no config on database and this will make others issuses related to config like this one.

I explained it to ask you what solution do you think would be better? 
should I manually order boot of these two packages or there is any better way.

ps: I think you should notice about removing filament-shield config file on UPGRADE section.
ممنون برادر

**Comment by bezhanSalleh** [comment]
will be fixed as well, becuase in PR #69 you can opt in/out of using db as settings' driver...
this change was made to handle edge cases like yours outta the box so you can work on what's important, until you implement you own edge-case fix.
Give the PR a look you will get the point.
