### ISSUE TITLE
Error  Argument #1 ($object_or_class) must be of type object|string, null given while updating

### ISSUE THREAD

**Issue by yammycode** [bezhanSalleh/filament-shield#86]
I have error when run shield:install comand:
<img width="1075" alt="Снимок экрана 2022-07-28 в 15 19 15" src="https://user-images.githubusercontent.com/65212344/181503532-491d89ad-0894-4a80-bec8-246a83dd26e1.png">
After i delete shield package and config file. But while new install i have same error. 
Any idea?

**Comment by DaedalusWings** [comment]
Me too.
![grafik](https://user-images.githubusercontent.com/5040277/181510562-fce10255-bbfc-4108-96ad-3fa4e789fb68.png)

**Comment by bezhanSalleh** [comment]
fixed and will be available in 2.1.0
