### ISSUE TITLE
I can access role page and edit role without permission

### ISSUE THREAD

**Issue by nicolasbaud** [bezhanSalleh/filament-shield#93]
Hello,

I have configure a new role without "Role" permission and if i'm log in the account which don't have role permission i view the page and if i edit role and i'm delete "disabled" variable with source i can edit the role.

Screenshots:

Role (super admin account):
![image](https://user-images.githubusercontent.com/63586531/183096526-68470113-ea60-4c1b-9596-ca4152ae92d7.png)

Role page (new account without permission): 
![image](https://user-images.githubusercontent.com/63586531/183096462-a703920a-b58a-4d18-baa2-de846f84db02.png)

Edit role (new account without permission):
![image](https://user-images.githubusercontent.com/63586531/183096609-8650ebfb-f39a-4c05-bb5d-a33e683f45f0.png)

**Comment by khanakia** [comment]
@bezhanSalleh There is one more big security bug. If i copy any request as CURL from Developer Tools and then update the token and send a request using Postman for the other user i can update, and delete any record so no policy is enforced.

**Comment by bezhanSalleh** [comment]
> Hello,
> 
> I have configure a new role without "Role" permission and if i'm log in the account which don't have role permission i view the page and if i edit role and i'm delete "disabled" variable with source i can edit the role.
> 
> Screenshots:
> 
> Role (super admin account): ![image](https://user-images.githubusercontent.com/63586531/183096526-68470113-ea60-4c1b-9596-ca4152ae92d7.png)
> 
> Role page (new account without permission): ![image](https://user-images.githubusercontent.com/63586531/183096462-a703920a-b58a-4d18-baa2-de846f84db02.png)
> 
> Edit role (new account without permission): ![image](https://user-images.githubusercontent.com/63586531/183096609-8650ebfb-f39a-4c05-bb5d-a33e683f45f0.png)

seems like you haven't configured it properly
`register_role_policy' => [
              'enabled' => false
 ]`
 set it to `true` to enforce the Role Policy

**Comment by bezhanSalleh** [comment]
> @bezhanSalleh There is one more big security bug. If i copy any request as CURL from Developer Tools and then update the token and send a request using Postman for the other user i can update, and delete any record so no policy is enforced.

don't really know what kinda magic are trying to achieve here, but shield only generates stuff for filament and the policies only get enforced if it follows the policy guidelines as laravel has set forth. other than that you would need to register them in the `AuthServiceProvider`...
