### ISSUE TITLE
roles and permission

### ISSUE THREAD

**Issue by dev-dhull** [bezhanSalleh/filament-shield#96]
Hii, When I install filament-shield(roles and permissions) my resources on the dashboard are hidden automatically. <-how do I resolve this issue?

**Comment by bezhanSalleh** [comment]
I assume, you are using the `HasFilamentShield` trait and you user was created before shield.
Just run `shield:super-admin`.

**Comment by dev-dhull** [comment]
> I assume, you are using the `HasFilamentShield` trait and you user was created before shield. Just run `shield:super-admin`.

Sorry but its not working

**Comment by bezhanSalleh** [comment]
ask these questions on discord channel, where everyone can help...
for now, run `php artisan shield:install --fresh`

**Comment by dev-dhull** [comment]
Sorry, this is not working.

**Comment by dev-dhull** [comment]
I am not using discord
 can u please help me to resolve this issue?
because PHP artisan shield:install --fresh command is not resolved my issue.
see this every resource tab are hidden.

[image: image.png]

**Comment by bezhanSalleh** [comment]
joing discord for filament ... https://filamentphp.com/discord
